### ISSUE TITLE
Can't do a Quick View of Sequential Aug similar to Readme

### ISSUE THREAD

**Issue by pGit1** [aleju/imgaug#10]
Hi Alex! This library is amazing!! However when running the code below I get this error: `
RuntimeError: Could not execute image viewer.`

`import augmenters as iaa`
`import numpy as np`

`images = np.random.randint(0, 255, (16, 128, 128, 3), dtype=np.uint8)`
`seq = iaa.Sequential([iaa.Fliplr(0.5), iaa.GaussianBlur((0, 3.0))])`

`seq.show_grid(images[0], cols=8, rows=8)`

`seq.show_grid([images[0], images[1]], cols=8, rows=8)`

**Comment by aleju** [comment]
I just tested the example and it worked for me. The library uses `scipy.misc.imshow()` to show the images and that function can throw such an error. You should try something like the following:
```python
from scipy import misc
import numpy as np
image = np.random.randint(0, 255, (128, 128, 3), dtype=np.uint8)
misc.imshow(image)
```
If that throws the same error then there might be something wrong with your scipy installation (i.e. that it can't find your image viewing program).

**Comment by pGit1** [comment]
Weird it threw the same error even after an upgrade to latest Scipy :(

Its ok. The library works perfect otherwise for my needs!!

**Comment by Hari-Sheng** [comment]
``imshow` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.'
I am going to open an issue for this part.

**Comment by iphyer** [comment]
yes, I am having the same problem.

```
 DeprecationWarning: `imshow` is deprecated!
`imshow` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``matplotlib.pyplot.imshow`` instead.
  after removing the cwd from sys.path.
```
Probabily we need to upgrade the functions to newest ones.
