### ISSUE TITLE
'BoundingBoxesOnImage' object has no attribute 'deepcopy' 

### ISSUE THREAD

**Issue by Adnation** [aleju/imgaug#101]
I am trying to project bounding boxes on rotated images but it throws this error. 
Here is the snippet I am trying.

```
    bbs = ia.BoundingBoxesOnImage(bound_boxes, shape=rot_90.shape)
    image_rescaled = seq_270_det.augment_images(rot_90)
    bbs_rescaled = bbs.on(image_rescaled)
    image_rescaled_bbs = bbs_rescaled.draw_on_image(
        image_rescaled, thickness=2)
```

To give you brief what I am doing is,

I have an image I rotate it by 90 degree and then I predict on this rotated image and then I want rotate image to original rotation. So for that I am rotating it with 270 degree and now I want to map predictions of 90 degree rotated images to the rotated images of 270 degree i.e. original image.

I've also tried keypoint augmentation as follows

1. Rotated original image by 90 degree (Which crops away some part of image)
2. Then I ran prediction on it which gave me bounding box coordinates
3. Now to rotate 90 degree image to original I rotated image by 270 degree. (It also cropped some part of image)
4. And then I also  ran keypoint augmentation for 270 degree but this points are quit out of order.

Please let me know what I am doing wrong here.

**Comment by aleju** [comment]
The deepcopy bug should be fixed now in master. Thanks for the info!
Not sure why you had problems with the keypoint augmentation being wrong though, that would require a code example.
