### ISSUE TITLE
Background Image Processing Hangs If Ungraceful Exit

### ISSUE THREAD

**Issue by AustinDoolittle** [aleju/imgaug#102]
A process using background image processing will hang if runtime is terminated before background image processing is complete.

### System:
- Operating System: Ubuntu 16.04
- Python: 2.7.12
- imgaug: 0.2.5

### Code to Reproduce
```python
import imgaug as ia
import numpy as np

def batch_generator():
    for i in range(10000):
        batch = ia.Batch(images=np.zeros((10,3,255,255)))
        yield batch

bg_loader = ia.BatchLoader(batch_generator)
bg_augmenter = ia.BackgroundAugmenter(bg_loader, ia.augmenters.Noop())

bg_augmenter.get_batch()
bg_augmenter.terminate()
bg_loader.terminate()
````

### Expected Result
Code exits gracefully and you go on with your life

### Actual Result
Parent process becomes zombie process and requires manual termination via PID

### Proposed solution
The queues owned by BatchLoader and BackgroundAugmenter should be closed in their respective terminate() calls.

**Comment by aleju** [comment]
Pull request was added to master, so should be fixed now and I'll close this issue now.
Thanks for the help!

**Comment by AustinDoolittle** [comment]
No problem, thanks for all your work on this project! It's a really useful
tool.
