### ISSUE TITLE
Could i make image's padding color not black?

### ISSUE THREAD

**Issue by zallmight** [aleju/imgaug#104]
thx

**Comment by amtf1019** [comment]
did you solve this problem?

**Comment by zallmight** [comment]
@amtf1019 yes, i did

**Comment by amtf1019** [comment]
How did you do that? I need help on this. Thanks!

**Comment by zallmight** [comment]
seq = iaa.Sequential([iaa.SomeOf((1, 3),
        [sometimes(iaa.Multiply((0.8, 1.2))), # change brightness, doesn't affect keypoints
            sometimes(iaa.Affine(
            scale={"x": (0.9, 1.1), "y": (0.9, 1.1)},
            cval=(167) 
        )), # rotate by exactly 10deg and scale to 50-70%, affects keypoints
        sometimes(iaa.PiecewiseAffine(scale=(0.01, 0.05)))
        ])
    ])

**Comment by amtf1019** [comment]
@zallmight Thanks, the works perfectly
