### ISSUE TITLE
realistic background ?

### ISSUE THREAD

**Issue by Borda** [aleju/imgaug#106]
Have you considered using a realistic background for the geometrical distortion instead only filling by a single color, for example using outer edge from the image and propagate it to the padding background?

**Comment by aleju** [comment]
Edge propagation is enabled in Affine, e.g. `Affine(mode="edge")` (or `Affine(mode=ia.ALL)`) and in PiecewiseAffine via the same interface. It is also available in ElasticTransformations, e.g. `ElasticTransformation(mode="nearest")` should do it I think. PerspectiveTransform doesn't offer it as it wraps around cv2.warpPerspective, which doesn't have such an option afaik.

If you mean with "realistic background" to add parts of real images instead, then I have thought about that, but it isn't that easy to implement as the base functions from skimage and cv2 don't offer that. So a constant color would have to be used as the first step and then in the second step the color would have to be replaced by the content of real images. That's a bit ugly and possibly slow. The interface to the augmenters might also become quite ugly, not sure.

**Comment by Borda** [comment]
Ok, thanks... I was just thinking about it while seeing the examples. I may try to do it and let's see if the result will be something reasonable...
