### ISSUE TITLE
What colourspace should the input image be?

### ISSUE THREAD

**Issue by Moataz-E** [aleju/imgaug#107]

**Comment by aleju** [comment]
RGB is the best choice. Ultimately it depends on the augmenter. E.g. `Grayscale` expects by default RGB. It offers an option to change the expected input colorspace, but colorspaces aside from RGB are usually not tested. Other augmenters like `AdditiveGaussianNoise`, `Dropout` or `Affine` should not care about the colorspace, so long as it has a value range of 0 to 255.

**Comment by Moataz-E** [comment]
Thanks, this was really useful. 

I will stick with using RGB.
