### ISSUE TITLE
augment_keypoints not actually deterministic when using to_deterministic()

### ISSUE THREAD

**Issue by parsoj** [aleju/imgaug#112]
In the below code - I start with three identical sets of KeypointsOnImage(), but applying a deterministic transformation leads to different results for different KeypointsOnImage() sets.

code block:

```
import imgaug as ia
from imgaug import augmenters as iaa

kps = [[ia.Keypoint(x=31, y=31),
        ia.Keypoint(x=563, y=31),
        ia.Keypoint(x=31, y=477),
        ia.Keypoint(x=563, y=477)],
       [ia.Keypoint(x=31, y=31),
        ia.Keypoint(x=563, y=31),
        ia.Keypoint(x=31, y=477),
        ia.Keypoint(x=563, y=477)],
       [ia.Keypoint(x=31, y=31),
        ia.Keypoint(x=563, y=31),
        ia.Keypoint(x=31, y=477),
        ia.Keypoint(x=563, y=477)]]

keypoint_sets = [ia.KeypointsOnImage(kp, shape=(600, 492, 3)) for kp in kps]

seq = iaa.Sequential(
    [
        iaa.Fliplr(0.5),
        iaa.Flipud(0.5),
    ]
)

seq_det = seq.to_deterministic()
keypoint_sets_aug = seq_det.augment_keypoints(keypoint_sets)

print("keypoint_sets: \n{}".format(keypoint_sets))
print("keypoint_sets_aug: \n{}".format(keypoint_sets_aug))
```

shell output (from running the above):
```
> python transmorgify.py 
keypoint_sets: 
[
  KeypointsOnImage([Keypoint(x=31, y=31), Keypoint(x=563, y=31), Keypoint(x=31, y=477), Keypoint(x=563, y=477)], shape=(600, 492, 3)),
  KeypointsOnImage([Keypoint(x=31, y=31), Keypoint(x=563, y=31), Keypoint(x=31, y=477), Keypoint(x=563, y=477)], shape=(600, 492, 3)),
  KeypointsOnImage([Keypoint(x=31, y=31), Keypoint(x=563, y=31), Keypoint(x=31, y=477), Keypoint(x=563, y=477)], shape=(600, 492, 3))
]

keypoint_sets_aug: 
[
  KeypointsOnImage([Keypoint(x=460, y=31), Keypoint(x=-72, y=31), Keypoint(x=460, y=477), Keypoint(x=-72, y=477)], shape=(600, 492, 3)),
  KeypointsOnImage([Keypoint(x=31, y=568), Keypoint(x=563, y=568), Keypoint(x=31, y=122), Keypoint(x=563, y=122)], shape=(600, 492, 3)),
  KeypointsOnImage([Keypoint(x=460, y=31), Keypoint(x=-72, y=31), Keypoint(x=460, y=477), Keypoint(x=-72, y=477)], shape=(600, 492, 3))
]
```

(the second KeypointsOnImage set is different in this case)

this does consistently reproduce for me

Please let me know if I'm miss-understanding the intended behavior of to_deterministic, but I believe that in this case, the expected behavior is for identical Keypoints to be transformed identically (even if they are in different groupings of KeypointsOnImage)

**Comment by aleju** [comment]
"deterministic" means that the augmentation process produces the same results if the input is the same AND the position in the batch is the same. Basically the RNG is reset at the *end* of the call to `augment_images()` or `augment_keypoints()`, but not *in between* images/keypoints. It is coincidence in your case that the third keypoint set is the same as the first one. Usually it would be different.

If you have several sets of keypoints and each one of them is supposed to be augmented in the identical way, you have to call `to_deterministic()` once and then `augment_keypoints([keypoints])` once per set of keypoints.

**Comment by parsoj** [comment]
Gotcha. Understood. 
I can confirm that calling augment_keypoints() multiple times as you suggested is giving me the behavior I want.
I'll close the issue since this looks to be expected. 

However - as an aside, regarding your comment on the third point being the same:
While testing I did pretty consistently see that pattern of two identical points and one different one. Maybe a race condition where the RNG is being reset before the function returns? Or maybe the RNG on my end is just boinked. 
Anyway - thank you!

**Comment by aleju** [comment]
> However - as an aside, regarding your comment on the third point being the same:
While testing I did pretty consistently see that pattern of two identical points and one different one. Maybe a race condition where the RNG is being reset before the function returns? Or maybe the RNG on my end is just boinked.

If you tested in all of these cases with horizontal and vertical flip at 50% probability each, you only get four possible outcomes with each having a probability of 25%. So it would not be unusual to get the same set of keypoints multiple times, but for longer augmentation sequences using augmenters with more continuous outcomes (e.g. Affine) it would be unusual and indicate a bug.
