### ISSUE TITLE
Install Script is a success

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#12]
Hello!
This is not an issue, but instead a review of the installation process.

The installation script has **successfully** worked for

1. virtualenvs
2. global installs
3. conda and anaconda 

tested with both python 2.7 and python3.5

This was good work !!! :+1:

**Comment by pGit1** [comment]
What install script? What is the install script?

**Comment by aleju** [comment]
You can now simply install via `sudo pip install imgaug` or `sudo pip install git+https://github.com/aleju/imgaug`.

**Comment by pGit1** [comment]
I realized that after I asked the question! Truly an amazing Library.
Thanks for your work on this.
