### ISSUE TITLE
AssertionError: Assertion failed.

### ISSUE THREAD

**Issue by prashant905** [aleju/imgaug#139]
I am trying to implement background augmentator with multiple image and large sets of keypoints.

Here is error:
Process Process-5:
Traceback (most recent call last):
  __File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imgaug/imgaug.py", line 1926, in _augment_images_worker
    batch.keypoints_aug = augseq_det.augment_keypoints(batch.keypoints)
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 531, in augment_keypoints
    ia.do_assert(all([isinstance(keypoints_on_image, ia.KeypointsOnImage) for keypoints_on_image in keypoints_on_images]))
  File "/usr/local/lib/python2.7/dist-packages/imgaug/imgaug.py", line 677, in do_assert
    raise AssertionError(str(message))
AssertionError: Assertion failed.__ 

Here is the code i am trying 
```
augseq = iaa.Sequential([
    iaa.Fliplr(0.5),
    iaa.CoarseDropout(p=0.1, size_percent=0.1)
])
fps = glob.glob('/notebooks/*.jpg')
kps = glob.glob('/notebooks/*.json')
# A generator that loads batches from the hard drive.
def load_batches():
    # Here, load 10 batches of size 4 each.
    # You can also load an infinite amount of batches, if you don't train
    # in epochs.
    batch_size = 2
    nb_batches = 2
    total_images = len(fps)
    count = 0
    for i in range(nb_batches):
        # A list containing all images of the batch.
        batch_images = []
        batch_keypoints = []
         batch_data = []
            # Add some images to the batch.
        for b in range(batch_size):
            print ("Image is:",fps[count])
            print ("json is:", kps[count])
            im  = cv2.imread(fps[count])
            keypoints = get_pandakeys(kps[count])            

            batch_images.append(im) 
            batch_keypoints.append(keypoints)

            count+=1
        batch = ia.Batch(
            images=np.array(batch_images, dtype=np.uint8),keypoints=batch_keypoints,
            data=batch_data
        )
        print("Finished_Batch",batch)
        yield batch
        batch_loader = ia.BatchLoader(load_batches)
        bg_augmenter = ia.BackgroundAugmenter(batch_loader, augseq)
       print("------------------")
print("augseq.augment_batches(batches, background=True)")
print("------------------")
batches = list(load_batches())
batches_aug = augseq.augment_batches(batches, background=True)
images_aug = []
keypoints_aug = []
for batch_aug in batches_aug:
    images_aug.append(batch_aug.images_aug)
    keypoints_aug.append(batch_aug.keypoints_aug)
plt.imshow(draw_grid(images_aug, keypoints_aug))
```

**Comment by aleju** [comment]
`get_pandakeys()` must return an instance of `imgaug.KeypointsOnImage()`, but doesn't seem to do that.
