### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ALL'

### ISSUE THREAD

**Issue by mathetes87** [aleju/imgaug#14]
In the example of "heavy augmentations" I get the error 
```
order=ia.ALL, # use any of scikit-image's interpolation methods
AttributeError: 'module' object has no attribute 'ALL'
```

I fixed this by replacing `ia.ALL` with `"ALL"`
Does the variable ALL accept other values?

PS: Great library. Very good work

**Comment by aleju** [comment]
You have some error in import the `imgaug.py` file as that should contain the constant `ALL`.
In the case of the `order` argument, `ALL` is equivalent to `[0, 1, 3, 4, 5]`. See [skimage's documentation](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.warp) for what they do. You probably want `order=1` or `order=0`, which are faster and usually enough.
In the case of the `mode` argument, `ALL` is equivalent to `["constant", "edge", "symmetric", "reflect", "wrap"]`, see again the documenation. `constant` is often enough.

**Comment by mathetes87** [comment]
Ok, thanks for the explanation!
