### ISSUE TITLE
images of different size in batch

### ISSUE THREAD

**Issue by prashant905** [aleju/imgaug#140]
Is there a way to read images of size in a batch and process. Since while loading them in batch they are put in numpy array using 
 `ia.Batch(
            images=np.array(batch_images, dtype=np.uint8), keypoints=batch_keypoints)
`

**Comment by aleju** [comment]
You should be able to use `ia.Batch(images=[image1, image2, ...], keypoints=batch_keypoints)`... or does that pattern not work for you? Not sure if ia.Batch() is unittested with it.

**Comment by prashant905** [comment]
Yeah, it works .thanks
