### ISSUE TITLE
Crop(keep_size = False) error

### ISSUE THREAD

**Issue by chuong98** [aleju/imgaug#143]
I want to crop a batch of images and keep them at the cropped size. Here is the code: 
`target_height = 272`
`target_width = 224`
`   v_crp = int((target_height - target_width)/2) `

`aug_crop = iaa.OneOf([iaa.Crop(px =(v_crp,0,v_crp,0),keep_size=False), `
                         ` iaa.Crop(px =(v_crp-4,0,v_crp+4,0),keep_size=False)  ])`
`augmenter = iaa.Sequential( [aug_crop],random_order=False)`
My batch input image is a numpy array  (n,272,224,3), and I want to crop the image to (n, 224,224,3).
Running 
`augmenter.augment_images(batch_x)`
 yields error 

> ValueError: shape mismatch: value array of shape (1,224,224,3) could not be broadcast to indexing result of shape (1,272,224,3)

Setting `keep_size = True` does not yield error, but it is not my purpose. Thanks

**Comment by aleju** [comment]
This is now fixed in master. Thanks for the report.
