### ISSUE TITLE
Issues with batch processing list out of range error

### ISSUE THREAD

**Issue by prashant905** [aleju/imgaug#145]
I am trying to implement batch processing with large images. But it returns me list out index error just after the batch. If I try to run the program no. of batch times manually , then it finishes successfully .
`Image_path = Imagepath
keypoint_files = keypoints path
save_path = path to save keypoints
batch_size =3
images = glob.glob(image_path)
keypts = glob.glob(keypoint_files)
batch_gen = ImageAugmentor(images, keypts, save_path, batch_size)
batch_loader = ia.BatchLoader(batch_gen.load_batch) 
bg_augmenter = ia.BackgroundAugmenter(batch_loader, batch_gen.aug_pipe)
batches = batch_gen.load_batch()
while True:
    batch = bg_augmenter.get_batch()
    print ("batch_type:",type(batch))
    if batch is None:
        print("Finished every batch.")
        break
    images_augment = batch.images_aug
    keypoints_augment = batch.keypoints_aug
    metakey = batch.data
    print ("Got batch ")
batch_loader.terminate()
bg_augmenter.terminate()`

I am getting this error:
`6
('Number of batches', 2)
Next batch...
('Finished_Batch', <imgaug.imgaug.Batch object at 0x7f3a51039f10>)
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imgaug/imgaug.py", line 1925, in _augment_images_worker
    batch.images_aug = augseq_det.augment_images(batch.images)
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 405, in augment_images
    hooks=hooks
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 1462, in _augment_images
    hooks=hooks
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 405, in augment_images
    hooks=hooks
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 1709, in _augment_images
    hooks=hooks
  File "/usr/local/lib/python2.7/dist-packages/imgaug/augmenters/meta.py", line 423, in augment_images
    if input_added_axis[i] == True:
IndexError: list index out of range`

**Comment by aleju** [comment]
First, update to to the latest version from master, maybe the problem was already fixed (I don't think so though). If it doesn't help, then can you maybe post a minimal working example, as otherwise this is going to be really hard to debug. It is an error that should essentially never happen. The following works as expected for me:
```python
from __future__ import print_function
import imgaug as ia
from imgaug import augmenters as iaa
import numpy as np

def load_batch():
    for _ in range(8):
        yield ia.Batch(
            images=[np.zeros((16, 16, 3), dtype=np.uint8) for _ in range(8)])

seq = iaa.Sequential([
    iaa.Affine(rotate=(-45, 45)),
    iaa.Dropout(0.02)
])

batch_loader = ia.BatchLoader(load_batch) 
bg_augmenter = ia.BackgroundAugmenter(batch_loader, seq)
while True:
    batch = bg_augmenter.get_batch()
    print ("batch_type:", type(batch))
    if batch is None:
        print("Finished every batch.")
        break
    images_augment = batch.images_aug
    #keypoints_augment = batch.keypoints_aug
    metakey = batch.data
    print ("Got batch ")
batch_loader.terminate()
bg_augmenter.terminate()
```
Output:
```
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <class 'imgaug.imgaug.Batch'>
Got batch 
batch_type: <type 'NoneType'>
Finished every batch.
```
