### ISSUE TITLE
How to transform Wide-angle picture to normal angle picture.

### ISSUE THREAD

**Issue by WuZhuoran** [aleju/imgaug#149]
I want to process the wide angle picture to normal angle.

![image](https://user-images.githubusercontent.com/8717187/42118060-4d4e7a24-7bb5-11e8-9c97-446ba4a13165.png)

Can we implement it with `imgaug`?

Thank you!

**Comment by aleju** [comment]
I think that's called a lens distortion transformation. That's currently not possible with the library, sorry. Might be added in the future.

**Comment by WuZhuoran** [comment]
@aleju  Thank you.

**Comment by arbsusbf** [comment]
![Uploading IMG_20230707_020659_316.jpg…]()

**Comment by arbsusbf** [comment]
Butterfly
