### ISSUE TITLE
How to define custom augmentation operation?

### ISSUE THREAD

**Issue by DangDinhQuocTrung** [aleju/imgaug#152]
In my use case, I need to place an image onto a random background. As there is no built-in operation for this purpose (but this library is still very comprehensive and awesome), I think I need to write a custom operation. I would like to ask if there is a way to do this or how to do this with existing operations. Thank you very much.

**Comment by aleju** [comment]
You can use the `Lambda` augmenter, which allows you to apply custom functions to images. A code example is below (untested). If that is not enough for your use case, you can take a look at `Fliplr` (horizontal flips) in `imgaug/augmenters/flip.py`. Its code is fairly easy to understand.

```python
backgrounds = np.random.randint(0, 256, size=(100, 128, 128, 3))

def func_images(images, random_state, parents, hooks):
    bg_ids = random_state.randint(0, len(backgrounds), size=(len(images),))
    result = []
    for image, bg_id in zip(images, bg_ids):
        image_small = ia.imresize_single_image(image, (64, 64))
        image_aug = np.copy(backgrounds[bg_id])
        image_aug[32:-32, 32:-32, :] = image_small
        result.append(image_aug)
    return result
    
def func_heatmaps(heatmaps, random_state, parents, hooks):
    return heatmaps
    
def func_keypoints(keypoints_on_images, random_state, parents, hooks):
    return keypoints_on_images

bg_augmenter = iaa.Lambda(
    func_images=func_images,
    func_heatmaps=func_heatmaps,
    func_keypoints=func_keypoints
)
seq = iaa.Sequential([
    iaa.Fliplr(0.5),
    bg_augmenter
])
```

**Comment by DangDinhQuocTrung** [comment]
Thank you very much.

**Comment by jcesquiveld** [comment]
Thanks. That helped a lot.
