### ISSUE TITLE
Conversion from RGB to HSV and back fails with OpenCV 3.x

### ISSUE THREAD

**Issue by cicobalico** [aleju/imgaug#157]
I get the following error every time I run code with 

`iaa.ChangeColorspace(from_colorspace="RGB", to_colorspace="HSV"),
iaa.ChangeColorspace(from_colorspace="HSV", to_colorspace="RGB"),`

The error is the following

`cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'
`
regferencing this line
https://github.com/aleju/imgaug/blob/1887d1e5bb2afa8ce94320f4bc7ab354753e9eda/imgaug/augmenters/color.py#L341

Any idea for a Fix?

**Comment by cicobalico** [comment]
after days of debugging obviously I found the fix to my own mistake after 40 minutes from opening the issue, sorry guys

**Comment by UPML** [comment]
what was the error? May be I have the same one.

**Comment by kumarnikhil936** [comment]
Hi @cicobalico What was the error?

**Comment by cicobalico** [comment]
I was trying to augment some images that had 7 channels with those augmenters (they were masks I needed to train my neural network). So obviously an error was thrown saying that my image didn't look like an image and it didn't know what to interpret as R G and B

**Comment by jamesacampbell** [comment]
@cicobalico what was the actual fixed conversion code that you used? I am running into the same error.

**Comment by cicobalico** [comment]
Sorry I didn’t have to change any code, I simply stopped feeding the masks to the augmentator and only fed it images with 3 channels, and the error stopped showing up

**Comment by jamesacampbell** [comment]
@cicobalico ok I will try that. Thanks

**Comment by Teeerry** [comment]
Hey, i met the same problem, but may be not the same as yours.
In my script, i **use the relative path for imread which caused the problem**, so i change the path (copy the image to current directory or use absolute path).

- Befor:

`img = cv2.imread("~/data/opencv-logo.png")
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)`

- Which lead to the problem:

> imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
> cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

- Solution for my problem:
`img = cv2.imread("opencv-logo.png")`

I hope it can help.

**Comment by aj85430** [comment]
@Teeerry , That's work. Thanks.

**Comment by mknekong** [comment]
img1 = cv2.imread('w1.jpg',0)
edges1=cv2.Canny(img1,100,200)
img_a=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

The error is:  Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

please tell me what is scn

**Comment by vivek-kumar9696** [comment]
hey...
This issue can also happen, not due to a problem with the code, but if another application is using the same webcam to capture video, or if another application which is using the same webcam was not closed properly.
Eg. when i had this problem, it was due to me running the code from jupyter notebook after I had just before run it from Spyder. Although the imshow windows were destroyed, the code from spyder was still capturing video from the same webcam as that of Jupyter's.
This caused absence of any video through the notebook and hence the image was a Nonetype

**Comment by xli2522** [comment]
@aleju Thanks a lot!

**Comment by LindsayFowler** [comment]
The following error message is given for too many different scenareos. It's even given when there is no image in the variable provided to use in the conversion. It would be nice if it said "could not find file" or something more understandible.


Exception has occurred: error
OpenCV(3.4.2) c:\miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\imgproc\src\color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'cv::CvtHelper<struct cv::Set<3,4,-1>,struct cv::Set<1,-1,-1>,struct cv::Set<0,2,5>,2>::CvtHelper'
  File "D:\Documents\Dropbox\Machine Learning\OpenCV\opencv_Basic_Facial_Detection.py", line 12, in <module>
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

**Comment by jamesacampbell** [comment]
Yep, I had same issue it wasnt even loading image in and gave this error. It should be explicit as you state.

**Comment by LindsayFowler** [comment]
I wasted an hour on that. To be fair, the documentation for open XV imread does warn that no error message is provided for a failed load.

Why? I guess due to the cv routines striving to be as fast and light weight as possible, perhaps descriptive errors are a luxury...

That leaves ordinary folk to sharpen our debugging skills or at least do a lot of print(img) type tests! 

Happy coding.
