### ISSUE TITLE
documents in detail

### ISSUE THREAD

**Issue by sdalxn** [aleju/imgaug#158]
Hi,   @aleju!
I think your work is very great and helpful!
But I think there is a bit of difficulty in using it. For example, in code segment, "image = ia.quokka(size=(256, 256))", I don't find the specification about function "quokka"
Is there document about all APIs in detail?
You have given a web address, "http://imgaug.readthedocs.io/en/latest/source/modules.html - API." But I find there are only some modules name list and no explanation in detail about APIs.

Don't  I find correct web address?
Thank you in advance.

**Comment by sdalxn** [comment]
And in the “Examples: Basics“ section：
A standard use case ，there are codes like below:
`from imgaug import augmenters as iaa

seq = iaa.Sequential([
    iaa.Crop(px=(0, 16)), # crop images from each side by 0 to 16px (randomly chosen)
    iaa.Fliplr(0.5), # horizontally flip 50% of the images
    iaa.GaussianBlur(sigma=(0, 3.0)) # blur images with a sigma of 0 to 3.0
])

for batch_idx in range(1000):
    # 'images' should be either a 4D numpy array of shape (N, height, width, channels)
    # or a list of 3D numpy arrays, each having shape (height, width, channels).
    # Grayscale images must have shape (height, width, 1) each.
    # All images must have numpy's dtype uint8. Values are expected to be in
    # range 0-255.
    images = load_batch(batch_idx)
    images_aug = seq.augment_images(images)
    train_on_images(images_aug)`

The codes are pseudocode? Becauce  I can not find  the definition of fucntion "load_batch" and "train_on_images"

**Comment by aleju** [comment]
The quokka function simply returns a numpy array of dtype uint8 and shape (H, W, 3), where the height H and width W are provided to the function as `ia.quokka(size=(H, W))`.
The functions and classes are basically all documented in detail in the code files. They should also be documented in the documentation under the link you gave -- not sure what went wrong where, I think that has worked in the past. Will have to check that.

And yes, in the example that you gave `load_batch` and `train_on_images` are not defined and will have to be implemented by the library user as these functions are very specific to the experiment that one runs.

**Comment by sdalxn** [comment]
@aleju 
Thank you for your rapid  response.

Actually, I have some trouble in understanding the examples you gave in readme or other Documents.
Such as:

`import imgaug as ia
from imgaug import augmenters as iaa
import numpy as np

ia.seed(1)

# Example batch of images.
# The array has shape (32, 64, 64, 3) and dtype uint8.
images = np.array(
    [ia.quokka(size=(64, 64)) for _ in range(32)],
    dtype=np.uint8
)

seq = iaa.Sequential([
    iaa.Fliplr(0.5), # horizontal flips
    iaa.Crop(percent=(0, 0.1)), # random crops
    # Small gaussian blur with random sigma between 0 and 0.5.
    # But we only blur about 50% of all images.
    iaa.Sometimes(0.5,
        iaa.GaussianBlur(sigma=(0, 0.5))
    ),
    # Strengthen or weaken the contrast in each image.
    iaa.ContrastNormalization((0.75, 1.5)),
    # Add gaussian noise.
    # For 50% of all images, we sample the noise once per pixel.
    # For the other 50% of all images, we sample the noise per pixel AND
    # channel. This can change the color (not only brightness) of the
    # pixels.
    iaa.AdditiveGaussianNoise(loc=0, scale=(0.0, 0.05*255), per_channel=0.5),
    # Make some images brighter and some darker.
    # In 20% of all cases, we sample the multiplier once per channel,
    # which can end up changing the color of the images.
    iaa.Multiply((0.8, 1.2), per_channel=0.2),
    # Apply affine transformations to each image.
    # Scale/zoom them, translate/move them, rotate them and shear them.
    iaa.Affine(
        scale={"x": (0.8, 1.2), "y": (0.8, 1.2)},
        translate_percent={"x": (-0.2, 0.2), "y": (-0.2, 0.2)},
        rotate=(-25, 25),
        shear=(-8, 8)
    )
], random_order=True) # apply augmenters in random order

images_aug = seq.augment_images(images)

`
What I understand and don't understand are:
1) "images" are a collection or list of images.
2) "seq = iaa.Sequential(...)", "seg" is a defined augmenters list and the defined operation sequence will be applied on each image in images. But because "random_order=True" and some parameters in some augmenter in seq are random, I think the transformation sequence applied on each image is different.
3) "images_aug = seq.augment_images(images)", In this section, I got augmented images.
4) If I want to known what augment operations are applied on each image in images,  how should I code?

which opinions I understand are right or wrong?

And in another example section:
`Quickly show example results of your augmentation sequence:

from imgaug import augmenters as iaa
import numpy as np

images = np.random.randint(0, 255, (16, 128, 128, 3), dtype=np.uint8)
seq = iaa.Sequential([iaa.Fliplr(0.5), iaa.GaussianBlur((0, 3.0))])

# show an image with 8*8 augmented versions of image 0
seq.show_grid(images[0], cols=8, rows=8)

# Show an image with 8*8 augmented versions of image 0 and 8*8 augmented
# versions of image 1. The identical augmentations will be applied to
# image 0 and 1.
seq.show_grid([images[0], images[1]], cols=8, rows=8)`
In this section you gave, you define original images that include 16 pictures and a simple sequence.
I cannot find function "augment_images" had been called,like as "images_aug = seq.augment_images(images)". So , I think the sentence "seq.show_grid(images[0], cols=8, rows=8)" call augment operation. Is it true? But I am confused that: We have only 16 pictures in original images, why we can get 64 images after calling  seq.show_grid? One image and one seq, get one new image, Isn't it?

I am really confused about these some days. Could you give me some helps？
Any response will be appreciated.

**Comment by aleju** [comment]
The API docs should work now again.

> What I understand and don't understand are:
>  "images" are a collection or list of images.

yes, images are a list of numpy arrays of shape (H,W,C) or a single numpy array of shape (N,H,W,C).

> "seq = iaa.Sequential(...)", "seg" is a defined augmenters list and the defined operation sequence will be applied on each image in images. But because "random_order=True" and some parameters in some augmenter in seq are random, I think the transformation sequence applied on each image is different.

yes

> "images_aug = seq.augment_images(images)", In this section, I got augmented images.

yes

> If I want to known what augment operations are applied on each image in images, how should I code?

That's currently not really possible in the library. One could hack a bit with hooks to find out which augmenters were executed, but also estimating which parameters were used and which samples were drawn from them would be non-trivial and probably require quite some monkey-patching.

> I cannot find function "augment_images" had been called,like as "images_aug = seq.augment_images(images)". So , I think the sentence "seq.show_grid(images[0], cols=8, rows=8)" call augment operation. Is it true?

yes

> But I am confused that: We have only 16 pictures in original images, why we can get 64 images after calling seq.show_grid? One image and one seq, get one new image, Isn't it?

The function `show_grid()` receives (a) one or more input images, (b) the number of columns of images to draw (per image from (a) ), (c) the number of rows of images to draw (per image from (a) ). So if columns C=8 and rows R=8 then `C*R = 8*8 = 64` images are drawn per image from (a). I.e. `show_grid(images[0], cols=8, rows=8)` draws 64 images as it gets a single input image (the first one in `images`). All drawn images are augmented versions of `images[0]`. The augmentation sequence `seq` is simply executed as often as necessary to get to `C*R`. That `images` contains 16 images here doesn't matter. It could also contain 1000 images and it wouldn't change anything, as show_grid only receives the first image from `images` (and in the second call it receives the first and second image).

**Comment by sdalxn** [comment]
@aleju ，Thank you for your replies!
 I think I can understand the library more correctly for your helps.

**Comment by sdalxn** [comment]
Oh, I have checked the APIs Document just one minute ago, and I got "Sorry, This page does not exist yet".

**Comment by aleju** [comment]
Which page did you try? This one works for me: http://imgaug.readthedocs.io/en/latest/source/api.html (also try manual refresh, readthedocs seems to use rather aggressive caching)

**Comment by sdalxn** [comment]
Oh, I access:http://imgaug.readthedocs.io/en/latest/source/modules.html - API.
The Page: http://imgaug.readthedocs.io/en/latest/source/api.html is OK.

**Comment by Malouke** [comment]
hello i am sorry but documentation it's not clear ,
when you apply this function 
aug = iaa.Affine(rotate=(-10,10) )  that mean you will get all rotetd image btween -45 and 45 
when you apply aug.augment_image(img)
where img it's np.array()

in example you  don't explain how you apply how you get all images bteween -45,to 45 ,and that remark it for all other affine application( translation .....)

why it's not clear ?

(i don't have no idea still now to get all intermediate image of rotate=(-45,45) ?)

**Comment by aleju** [comment]
Not sure what you mean here, if you just want many images with rotations in the range `[-45, 45]` you can use
```python
images_aug = iaa.Affine(rotate=(-45, 45)).augment_images([image] * N)
```
where `N` is the number of augmented images to create. Each of them will have a random rotation in the described range.

**Comment by Malouke** [comment]
thx ,
