### ISSUE TITLE
Get current affine transform values

### ISSUE THREAD

**Issue by SergeyMalashenko** [aleju/imgaug#164]
Good day! How to do it?

**Comment by SergeyMalashenko** [comment]
You can add key points and apply for them the same affine transforms. And after that calculate transformation


def get_affine_transform( fromKeypoint_s, toKeypoint_s ):
        A = np.zeros((len( fromKeypoint_s )*2,6))
        b = np.zeros((len( fromKeypoint_s )*2, )) 

        for i in range( len( fromKeypoint_s ) ):
                fromKeypoint = fromKeypoint_s[i]
                toKeypoint   = toKeypoint_s  [i]
                
                A[2*i + 0] = np.array([ fromKeypoint[0], fromKeypoint[1], 1,               0,               0, 0])
                A[2*i + 1] = np.array([               0,               0, 0, fromKeypoint[0], fromKeypoint[1], 1])
                b[2*i + 0] = toKeypoint[0]
                b[2*i + 1] = toKeypoint[1]
                
        x = linalg.lstsq(A,b)[0]
        return x.reshape( (2,3) )

**Comment by aleju** [comment]
Deriving the affine transformation matrix from keypoints should work if you really only care about Affine (and do not have e.g. cropping in your augmentation sequence).
As an alternative, you can also use `Affine._draw_samples()` as a helper to achieve your goal.
E.g. something like
```python
images = ...
aug = Affine(...)
random_state_copy = ia.copy_random_state(aug.random_state)
scale_samples, translate_samples, rotate_samples, shear_samples, cval_samples, mode_samples, order_samples = aug._draw_samples(len(images), random_state_copy)
images_aug = aug.augment_images(images)
```
then `scale_samples, translate_samples, rotate_samples, shear_samples` contain the scalings, translations, rotations and shearings of each affine transformation that was applied during `images_aug = aug.augment_images(images)`. They can be transformed to affine transformation matrices with something like
```python
import math
from skimage import transform as tf

i = <index of image>
h = <height of image>
w = <width of image>

shift_y = h / 2.0 - 0.5
shift_x = w / 2.0 - 0.5
scale_x, scale_y = scale_samples[0][i], scale_samples[1][i]
translate_x, translate_y = translate_samples[0][i], translate_samples[1][i]
if ia.is_single_float(translate_y):
    translate_y_px = int(round(translate_y * h))
else:
    translate_y_px = translate_y
if ia.is_single_float(translate_x):
    translate_x_px = int(round(translate_x * w))
else:
    translate_x_px = translate_x
rotate = rotate_samples[i]
shear = shear_samples[i]

matrix_to_topleft = tf.SimilarityTransform(translation=[-shift_x, -shift_y])
matrix_transforms = tf.AffineTransform(
    scale=(scale_x, scale_y),
    translation=(translate_x_px, translate_y_px),
    rotation=math.radians(rotate),
    shear=math.radians(shear)
)
matrix_to_center = tf.SimilarityTransform(translation=[shift_x, shift_y])
matrix = (matrix_to_topleft + matrix_transforms + matrix_to_center)
```
then `matrix.params` should contain the affine transformation matrix.
