### ISSUE TITLE
How to get identity transform?

### ISSUE THREAD

**Issue by SergeyMalashenko** [aleju/imgaug#167]
Good day! Subj

**Comment by aleju** [comment]
If you mean that you don't want to change images, then you can just use Noop, e.g.
```python
seq = iaa.Noop()
images_aug = seq.augment_images(images)
```
then `images_aug` contains a copy of `images`.
Most other augmenters also default to do nothing if no parameters are provided. E.g. `Affine()` should not change images.

**Comment by SergeyMalashenko** [comment]
Thank you!
