### ISSUE TITLE
Is there a overflow consideration

### ISSUE THREAD

**Issue by zhly0** [aleju/imgaug#177]
Hi aleju,this is not a issue,but a question.
In the imgaug,there are many functions ,like add.let say,a pixel add value 30 ,and the original value is 240,and the added value > 255,is the imgaug will clip the value to 255 when the value >255 or to 0 when the value <0?
Thanks!

**Comment by aleju** [comment]
In case of overflows the augmenters should clip to the range [0, 255].

**Comment by zhly0** [comment]
Thanks!

**Comment by trihook** [comment]
> In case of overflows the augmenters should clip to the range [0, 255].

how to clip to the range[0,255]

**Comment by trihook** [comment]
> In case of overflows the augmenters should clip to the range [0, 255].
@aleju 
how to clip to the range[0,255]?
i did not find the parameter to set

**Comment by aleju** [comment]
If you feed in ordinary `uint8` images, the library will automatically make sure that everything stays within [0, 255] and will return `uint8` again. You don't have to clip yourself and there is currently no dedicated way to do that. (Though if you really wanted to, you could do it by wrapping `numpy.clip()` in a `Lambda` augmenter.)
