### ISSUE TITLE
Update the plotting function to show images?

### ISSUE THREAD

**Issue by iphyer** [aleju/imgaug#179]
Hi, great repository and great work.
However, when I was using it, I found it relies on `scipy` to show images.
And according to `scipy` documents [scipy.misc.imshow](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imshow.html), I guess the `scipy.imshow()` is downgraded.

```
 DeprecationWarning: `imshow` is deprecated!
`imshow` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``matplotlib.pyplot.imshow`` instead.
  after removing the cwd from sys.path.

```

Also, we need to install `Pillow` to use this function.

```
Simple showing of an image through an external viewer.

This function is only available if Python Imaging Library (PIL) is installed.

Uses the image viewer specified by the environment variable SCIPY_PIL_IMAGE_VIEWER, or if that is not defined then see, to view a temporary file generated from array data.
```

**Comment by aleju** [comment]
Did you get that warning with the pypi version? The latest one in master should no longer use scipy's imshow, but instead the one from matplotlib.

**Comment by iphyer** [comment]
@aleju Yes, I am using an older version of PiPy to suit the PyCharm IDE. Well, I will try to update the version to check this out. Thank you!

**Comment by iphyer** [comment]
pip verison `10.0.1` is that OK?

**Comment by aleju** [comment]
I mean whether you installed via `pip install imgaug` or something like `pip install git+https://github.com/aleju/imgaug.git` (or via `git clone` + `python setup.py`). The first method will cause the warning as that version still uses the deprecated functions. The second method would install a newer version of the library from github and should not lead to the warning. Your version of `pip` should not influence this problem.

**Comment by iphyer** [comment]
@aleju Hi still seeing this  error

```
Adapting to protocol v5.1 for kernel 6deadefd-8f4c-4d92-b9a7-0642a8247bfb
sh: see: command not found
```

**Comment by aleju** [comment]
Can you post the full stacktrace?

Also, see if the following code works for you:
```python
import matplotlib.pyplot as plt
import numpy as np
plt.imshow(np.zeros((32, 32, 3), dtype=np.uint8))
plt.show()
```

**Comment by iphyer** [comment]
@aleju Thank you!
I can see how this works with `matplotlib`. And my problem is that I can now run this demo code:

```python

from imgaug import augmenters as iaa
import numpy as np
import matplotlib.pyplot as plt


images = np.random.randint(0, 255, (16, 128, 128, 3), dtype=np.uint8)
seq = iaa.Sequential([iaa.Fliplr(0.5), iaa.GaussianBlur((0, 3.0))])


# Show an image with 8*8 augmented versions of image 0 and 8*8 augmented
# versions of image 1. The identical augmentations will be applied to
# image 0 and 1.
seq.show_grid([images[0], images[1]], cols=8, rows=8)

```
Error is still the same:

```
in imshow(arr)
    505     os.unlink(fname)
    506     if status != 0:
--> 507         raise RuntimeError('Could not execute image viewer.')
    508 
    509 

RuntimeError: Could not execute image viewer.
```

**Comment by aleju** [comment]
You example code works for me.

> I can see how this works with matplotlib.

Do you mean that the matplotlib code worked for you? Because either both or none of these should work for you. If the matplotlib code succeeds but the demo code that you posted fails then there is probably still an old version of the library installed. The stacktrace that you posted seems indeed like it is outdated (code lines fit scipy's imshow). Try `pip uninstall imgaug && pip install --upgrade git+https://github.com/aleju/imgaug.git` and make sure that there are no errors.

If you still get an error when running the demo code, please post a longer stacktrace.

**Comment by iphyer** [comment]
Sure, thank you.
I fixed it.
Best!
