### ISSUE TITLE
Understanding of Function "Sometimes()"

### ISSUE THREAD

**Issue by pengpaiSH** [aleju/imgaug#18]
@aleju Thank you for providing such an amazing package which makes convenient for training deep networks for visual recognition. In the example codes, 
```
# Sometimes(0.5, ...) applies the given augmenter in 50% of all cases,
# e.g. Sometimes(0.5, GaussianBlur(0.3)) would blur roughly every second image.
st = lambda aug: iaa.Sometimes(0.5, aug)
```
I am still confused by the functionality of ```Sometimes(0.5)```, would you please give more comments on this function? Thank you .

**Comment by aleju** [comment]
Something like
```python
iaa.Sequential(
    ...
    iaa.Sometimes(0.5, iaa.GaussianBlur((0.1, 0.3))
    ...
)
```
would mean, that only in 50% of all cases gaussian blur with a random strength between 0.1 and 0.3 is applied. So basically 50% of all images are not affected by any form of gaussian blur. The Sequential simply skips that augmenter completely in these cases, as if it didn't contain it.

**Comment by pengpaiSH** [comment]
@aleju Thank for you feedback! However, the ```Horizontal_Flip(0.5)``` operation does not need a ``Sometimes()````, right?

**Comment by aleju** [comment]
Yes, horizontal and vertical flips don't need it.
