### ISSUE TITLE
setup.py cannot detect cv2 in conda environment

### ISSUE THREAD

**Issue by KokeCacao** [aleju/imgaug#194]
Reproduction:

*1
- install cv2 in conda environment -> success
- install imgaug in conda environment -> failed because no cv2 installed

*2
- install cv2 in base environment -> success
- install imgaug in conda environment -> failed because no cv2 installed

*3
- install cv2 in base environment -> success
- install imgaug in base environment -> success

Error when failed:
```
pip install git+https://github.com/aleju/imgaug
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to /tmp/pip-req-build-u129c1er
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-req-build-u129c1er/setup.py", line 11, in <module>
        import cv2 # pylint: disable=locally-disabled, unused-import, line-too-long
    ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-u129c1er/setup.py", line 13, in <module>
        raise Exception("Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.")
    Exception: Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.
```

**Comment by aleju** [comment]
I don't use conda, so I can't say anything for sure here. You have to make sure to install both OpenCV and imgaug in conda - and not accidentally one of them outside of that environment.
imgaug will then merely check if it can import `cv2`. This should work, unless conda uses a different package name for OpenCV (which I don't think it does). The error `ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type` makes it seem like there is some problem with your installation of OpenCV. Try running just `python` in conda and then do `import cv2`. It will likely also cause an error.

**Comment by KokeCacao** [comment]
> I don't use conda, so I can't say anything for sure here. You have to make sure to install both OpenCV and imgaug in conda - and not accidentally one of them outside of that environment.
> imgaug will then merely check if it can import `cv2`. This should work, unless conda uses a different package name for OpenCV (which I don't think it does). The error `ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type` makes it seem like there is some problem with your installation of OpenCV. Try running just `python` in conda and then do `import cv2`. It will likely also cause an error.

Sorry for the confusion.
I used the command `pip install opencv-python` when I tried to install opencv both in and out of conda environment. (which means they are the same package but under different environment).
Indeed, installing cv2 in conda environment does give an error when I tried to import it directly using the console. I guess the strange behavior of cv2 is where to blame?

(correct me if I am wrong)

**Comment by aleju** [comment]
> Indeed, installing cv2 in conda environment does give an error when I tried to import it directly using the console. I guess the strange behavior of cv2 is where to blame?

At least you shouldn't get an error when just importing cv2. Maybe it is supposed to be installed in a different way in conda? I guess this would be a question for stackoverflow. [here](https://stackoverflow.com/questions/43019951/after-install-ros-kinetic-cannot-import-opencv) is somebody with the same error message who also used ROS at least.

**Comment by KokeCacao** [comment]
> > Indeed, installing cv2 in conda environment does give an error when I tried to import it directly using the console. I guess the strange behavior of cv2 is where to blame?
> 
> At least you shouldn't get an error when just importing cv2. Maybe it is supposed to be installed in a different way in conda? I guess this would be a question for stackoverflow. [here](https://stackoverflow.com/questions/43019951/after-install-ros-kinetic-cannot-import-opencv) is somebody with the same error message who also used ROS at least.

That is it!
ROS is the one that caused all these problems. I used ROS a month ago, too. Thank you for your reply.
