### ISSUE TITLE
augment mask

### ISSUE THREAD

**Issue by VCBE123** [aleju/imgaug#196]
When i use the example to augment the mask, there is no method named 'augment_segmentation_maps'

**Comment by aleju** [comment]
Which version did you use? Try the latest one from github via `pip install git+https://github.com/aleju/imgaug`. The one on pypi might not have that method yet as it is quite new.

**Comment by VCBE123** [comment]
pip install git+https://github.com/aleju/imgaug
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to /tmp/pip-req-build-02www0xk
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Command "git clone -q https://github.com/aleju/imgaug /tmp/pip-req-build-02www0xk" failed with error code 128 in None

**Comment by VCBE123** [comment]
I just tried it again, It done were. Beside that, why not add CLAHE( contrast limited adaptive histogram equalization) to the repo. Thank u for the awesome work.
