### ISSUE TITLE
Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by MetaDev** [aleju/imgaug#205]
I am doing a scale augmentation which seems to work fine for most images but feels for some.
At some point I get an error in the opencv part of the scale.

I found that this type of error can be thrown when the image is None.
Which might be caused by a problem I reported in: #204 

My output:

Epoch 1/50
 165/3150 [>.............................] - ETA: 19:44 - loss: 0.2758 - 0_conv_1x1_parts_loss: 0.1672 - 1_conv_1x1_parts_loss: 0.1086 - 0_conv_1x1_parts_acc: 0.0689 - 1_conv_1x1_parts_acc: 0.0761Traceback (most recent call last):
  File "train.py", line 62, in <module>
    batch_size=args.batch_size)
  File "../net/hourglass.py", line 65, in trainMPII2
    epochs=epochs, callbacks=xcallbacks)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 2212, in fit_generator
    generator_output = next(output_generator)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/keras/utils/data_utils.py", line 779, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/keras/utils/data_utils.py", line 644, in _data_generator_task
    generator_output = next(self._generator)
  File "../data_gen/mpII_datagen2.py", line 149, in generator
    image_aug = img_scale.augment_image(image_aug)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/imgaug/augmenters/meta.py", line 323, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/imgaug/augmenters/meta.py", line 431, in augment_images
    hooks=hooks
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/imgaug/augmenters/size.py", line 226, in _augment_images
    image_rs = ia.imresize_single_image(image, (h, w), interpolation=sample_ip)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/imgaug/imgaug.py", line 568, in imresize_single_image
    rs = imresize_many_images(image[np.newaxis, :, :, :], sizes, interpolation=interpolation)
  File "/media/ssddata/jstaley/miniconda3/envs/py35/lib/python3.5/site-packages/imgaug/imgaug.py", line 534, in imresize_many_images
    result_img = cv2.resize(images[img_idx], (width, height), interpolation=ip)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by aleju** [comment]
This should be the same underlying problem as in #204 (zero-sized images causing here image resizing to error), which seems to be fixed. So I close this one as its more or less a duplicate.

**Comment by newacronym** [comment]
use try and catch

**Comment by IdoZada** [comment]
I have the same problem , but i dont know how to solve it.
Please if someone knows to help I am happyness
![image](https://user-images.githubusercontent.com/48810056/84287717-f08d2b80-ab48-11ea-94e3-1523ced3b935.png)

**Comment by rakeshreddyrocky** [comment]
> I have the same problem , but i dont know how to solve it.
> Please if someone knows to help I am happyness
> ![image](https://user-images.githubusercontent.com/48810056/84287717-f08d2b80-ab48-11ea-94e3-1523ced3b935.png)

same problem bro chould you please help me

**Comment by ZhongQiyu** [comment]
> use try and catch

I don't think there are try and catch statements that are equivalent in Python?

**Comment by ZhongQiyu** [comment]
I looked through mine, being like:

```
import cv2 as cv

// Load face-detection model
face_net = cv.dnn.readNet('face-detection-adas-0001.xml', 'face-detection-adas-0001.bin')

// load age-gender detection model
age_gender_net = cv.dnn.readNet("age-gender-recognition-retail-0013.bin", "age-gender-recognition-retail-0013.xml")

// Specify target device for the face detection model (CPU)
face_net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

// Specify target device for the age-gender model (CPU)
age_gender_net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)

// set up labels for gender     
GENDER_LABELS = ['Female', 'Male']

// Read an image
frame = cv.imread('faces.jpg')
print(frame.shape)
     
// Prepare input blob
blob = cv.dnn.blobFromImage(frame, size=(672, 384), ddepth=cv.CV_8U)

// Perform inference (face detection)
face_net.setInput(blob)
out = face_net.forward()
     
// for each detected face 
for detection in out.reshape(-1, 7):
    confidence = float(detection[2])

    if confidence > 0.5:
     
        xmin = int(detection[3] * frame.shape[1])
        ymin = int(detection[4] * frame.shape[0])
        xmax = int(detection[5] * frame.shape[1])
        ymax = int(detection[6] * frame.shape[0])

        // draw rectangle over face 
        cv.rectangle(frame, (xmin, ymin), (xmax, ymax), color=(0, 255, 0))

        // perform age-gender detection
        // -->fill your code in ???..Tips:based on detected rectangle to recognise face on 62x62 image
        blob2=cv.dnn.blobFromImage(frame[xmin:xmax, ymin:ymax], size=(62,62), ddepth=cv.CV_8U)
        age_gender_net.setInput(blob2)
        detections = age_gender_net.forwardAndRetrieve(['prob','age_conv3'])
        
        // process results (age, gender)
        gender=GENDER_LABELS[detections[0][0][0].argmax()]
        age=int(detections[1][0][0][0][0][0] * 100)
        text=gender + " : " + str(age)

        // print results to image
        // --> your code here..Tip:put the text on the picture
        cv.putText(detection,text,(xmin,ymin),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),1)

// Save the frame to an image file
cv.imwrite('age_gender_output.png', frame)
```

I think the main issue is that the size of the image that I attempted to crop mistakes the height and width. Trying to fix it right now..
