### ISSUE TITLE
Shuffle Channel

### ISSUE THREAD

**Issue by AshStuff** [aleju/imgaug#206]
Is there a way to shuffle the channels in an Image ?

**Comment by aleju** [comment]
Not yet possible in the library -- you might be able to do something in that direction by combining `OneOf` with many `WithChannels`, but that would be fairly ugly code. I'll add it to the TODO list.

**Comment by aleju** [comment]
There is now a `ChannelShuffle` augmenter and a `shuffle_channels()` function. See [API doc](https://imgaug.readthedocs.io/en/latest/source/api_augmenters_meta.html#imgaug.augmenters.meta.ChannelShuffle) for the augmenter. Was already added a few weeks or so ago, but forgot to link this issue in the commit, sorry.
