### ISSUE TITLE
Affine operations result in a cropped image or black margins

### ISSUE THREAD

**Issue by eddiesmo** [aleju/imgaug#21]
Hi, thanks for writing this repo! It's a great help in what I do :)

One question: 
When I scale the image by 1.5 (affine transform) I lose information in the sides (it's more of a zoom than a resize function). Is there any way to simply resize the image?

Similar examples would be:
- When I use affine to scale the image by 0.5, I'm getting an image with a lot of black and have to perform a crop later
- When I rotate an image, the corners become cropped in the result.

The solution I am looking for is something like adding a flag "canvas_fits_image" which will perform the affine transformation and resize the canvas accordingly.

If it doesn't exist, I might add it myself sometime. Thanks!

**Comment by aleju** [comment]
The Affine class is currently a wrapper around scikit-image's [warp](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.warp) function. As far as I know, that function does not have a simple method to achieve that. It sounds like what you want matches more [scipy.misc.imresize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imresize.html) (only scales images though) and there is currently no wrapper for that function.

**Comment by eddiesmo** [comment]
Thanks for the response! I've implemented a couple of new quick and dirty augmenters for myself for now - in a few days I'll write it more cleanly and do a PR.
