### ISSUE TITLE
Hue and Saturation

### ISSUE THREAD

**Issue by isarandi** [aleju/imgaug#210]
I wanted to port a [color distortion augmentation from the TensorFlow repo](https://github.com/tensorflow/models/blob/23376e62928486712f6a5cff260c93d0b795bdc0/research/inception/inception/image_processing.py#L164) to imgaug.

There are two issues which made this non-straightforward:

1. Currently there is only `iaa.AddToHueAndSaturation`, while the TensorFlow code multiplies the saturation.
2. As far as I can tell by looking at the source, `iaa.AddToHueAndSaturation` doesn't handle the hue correctly: it's an angle and therefore requires modular arithmetic, not clipping after addition.

I ended up implementing it like this:

```python

def AddToHue(*args, **kwargs):
    # Hue is stored in OpenCV as 0-180, which actually stands for 0-360 degrees, but
    # 360 cannot fit in 8 bits, so they divide by two.
    return iaa.WithColorspace(
        to_colorspace='HSV', from_colorspace='RGB',
        children=iaa.WithChannels(channels=[0], children=AddModulo(180, *args, **kwargs)))


def MultiplySaturation(*args, **kwargs):
    return iaa.WithColorspace(
        to_colorspace='HSV', from_colorspace='RGB',
        children=iaa.WithChannels(channels=[1], children=iaa.Multiply(*args, **kwargs)))


class AddModulo(iaa.Add):
    """Like Add, but before clipping the value to 0-255 it computes value % `modulus`"""

    def __init__(self, modulus, *args, **kwargs):
        if not 0 <= modulus <= 255:
            raise ValueError('The modulus must be between 0 and 255')
        self.modulus = modulus
        super().__init__(*args, **kwargs)

    def _augment_images(self, images, random_state, parents, hooks):
        input_dtypes = meta.copy_dtypes_for_restore(images, force_list=True)
        result = images
        nb_images = len(images)
        seeds = random_state.randint(0, 10 ** 6, (nb_images,))
        for i in range(nb_images):
            image = images[i].astype(np.int32)
            rs_image = ia.new_random_state(seeds[i])
            per_channel = self.per_channel.draw_sample(random_state=rs_image)
            if per_channel == 1:
                nb_channels = image.shape[2]
                samples = self.value.draw_samples(
                    (nb_channels,), random_state=rs_image).astype(image.dtype)
                for c, sample in enumerate(samples):
                    ia.do_assert(-255 <= sample <= 255)
                    image[..., c] += sample
            else:
                sample = self.value.draw_sample(random_state=rs_image).astype(image.dtype)
                ia.do_assert(-255 <= sample <= 255)
                image += sample

            # THIS LINE WAS MODIFIED FROM `iaa.Add`, by inserting `np.mod`:
            image = meta.clip_augmented_image_(np.mod(image, self.modulus), 0, 255)
            image = meta.restore_augmented_image_dtype_(image, input_dtypes[i])
            result[i] = image
        return result

aug_like_tf = iaa.Sequential([
            iaa.Add((-32, 32)),
            iaa.ContrastNormalization((0.5, 1.5)),
            MultiplySaturation((0.5, 1.5)),
            AddToHue((-36, 36))], random_order=True)

```

I'm not sure if some part of this is useful for the codebase and how to best go about adding it in accordance with the overall design.

**Comment by aleju** [comment]
Interesting -- was not aware of hue being saved in that way by opencv. Using modulo makes a lot of sense in that case and should be incorporated into the library. Not entirely sure what the best way to achieve that is yet. One option would be to add an `overflow` parameter to `Add` that can be set to `"modulo"` with an additional `module_value` parameter that defaults to `255` and could be set to `180`. Though that would require handling the channels differently in `AddToHueAndSaturation` and could be inefficient. Might also make sense to implement `AddToHueAndSaturation` with its own algorithms, i.e. not by returning a set of other augmenters.

**Comment by aleju** [comment]
There is now a fixed version of `AddToHueAndSaturation` in master. `AddToHue` and `MultiplySaturation` will be added later on.
