### ISSUE TITLE
can not use tuple input for MotionBlur method

### ISSUE THREAD

**Issue by jdhao** [aleju/imgaug#215]
The MotionBlur documentation says that we can use tuple for parameter `k`. I have met an error when using tuple input:

> Traceback (most recent call last):
>   File "F:\sourceCode\img_add_noise_blur\add_blur.py", line 51, in <module>
>     main()
>   File "F:\sourceCode\img_add_noise_blur\add_blur.py", line 45, in main
>     im_arr = blurer.augment_image(im_arr)
>   File "D:\Anaconda\lib\site-packages\imgaug-0.2.6-py3.6.egg\imgaug\augmenters\meta.py", line 407, in augment_image
>     return self.augment_images([image], hooks=hooks)[0]
>   File "D:\Anaconda\lib\site-packages\imgaug-0.2.6-py3.6.egg\imgaug\augmenters\meta.py", line 511, in augment_images
>     hooks=hooks
>   File "D:\Anaconda\lib\site-packages\imgaug-0.2.6-py3.6.egg\imgaug\augmenters\convolutional.py", line 128, in _augment_images
>     matrices = self.matrix(images[i], nb_channels, ia.new_random_state(seed+i))
>   File "D:\Anaconda\lib\site-packages\imgaug-0.2.6-py3.6.egg\imgaug\augmenters\blur.py", line 515, in create_matrices
>     matrix = np.zeros((k_sample, k_sample), dtype=np.float32)
> TypeError: 'numpy.float64' object cannot be interpreted as an integer
> 

If I use single int, this function works ok. My code is like the following:

    from PIL import Image
    im = Image.open('test.jpg')
    im_arr = np.asarray(im)
    # blurer = iaa.GaussianBlur(sigma=(0.5, 2.5))
    # blurer = iaa.AverageBlur(4)
    blurer = iaa.MotionBlur(k=(3, 5), angle=180)
    im_arr = blurer.augment_image(im_arr)
    im = Image.fromarray(im_arr)
    im.show()

**Comment by aleju** [comment]
Thanks for reporting this! It is now fixed in master.

**Comment by jdhao** [comment]
Thanks for the prompt reply.
