### ISSUE TITLE
Cannot install opencv and imgaug in the same `pip install` line

### ISSUE THREAD

**Issue by craigcitro** [aleju/imgaug#218]
Repro steps:

* make a fresh virtualenv
* run `python3 -m pip install imgaug opencv-python`

Want: imgaug and cv2 are both installed
Got: error during imgaug setup.py, nothing is installed.

The problem here is that `setup.py` is looking for `cv2` to already be installed, which it may not yet be.

My use case is installing `imgaug` along with several other packages via `pip3 install -r requirements.txt`; I understand that there's an env var to skip this check, but I'd rather not start collecting env vars in every script that wants to set up an environment this way.

**Comment by aleju** [comment]
For the pip install statement it would help to just invert the order, but I guess that won't help for the requirements.txt file... Not sure what the best way is to solve this. I might turn the cv2 in the installer into a warning or make python-opencv a fixed dependency.

**Comment by aleju** [comment]
Yes, maybe that's the best way. So far I haven't done that because there are other ways to install OpenCV and thereby get `cv2` in python, while I think `python-opencv`'s `cv2` overwrites/dominates these. Might still be the best option overall.

**Comment by aleju** [comment]
The latest version in master now requires opencv-python as a dependency and has no more cv2 check in setup.py. Thanks for the suggestion.

**Comment by craigcitro** [comment]
Awesome, thanks @aleju! 

Is there any vague plan for when a new release including this change might happen? (I'm just looking to remove the workaround on our side.)

**Comment by aleju** [comment]
The plan was "sometime in January". Hard to tell if it will work out.

**Comment by aleju** [comment]
Version 0.2.8 is now on pypi.
