### ISSUE TITLE
Make Rot90 direction clear

### ISSUE THREAD

**Issue by ck244** [aleju/imgaug#223]
First off thanks so much for this tool! I think it's really helpful for preparing datasets.

I just wanted to mention something I found while working with the Rot90 augmenter. I was rotating my images with PIL and found that the direction of rotation was opposite. PIL rotates images counterclockwise (ROTATE_90 means to the left), while Rot90 rotates the bounding box clockwise. So I had to do 3 Rot90's to get the same as PIL's ROTATE_90. 

Guess it's not really an issue with the implementation, just would be useful to note this in the documentation. Thanks again!

**Comment by aleju** [comment]
The documentation actually already says that, see e.g. https://imgaug.readthedocs.io/en/latest/source/api_augmenters_geometric.html#imgaug.augmenters.geometric.Rot90 . Though it was changed quite recently from counter-clockwise to clockwise and I think at that point the word "clockwise" was also added to the docs (before there was no note about the direction). So it's possible that you looked at an older version of the documentation or code that didn't contain the direction yet. Or did you expect to see such a note somewhere else?

**Comment by ck244** [comment]
Ah, looks like I missed that, thanks for clarifying. I think I was looking at the main README, but the docs should be the definite answer. I guess it's up to you whether you think it's worth updating in the readme as well.

**Comment by aleju** [comment]
Readme is now updated in master, thanks for the suggestion.
