### ISSUE TITLE
Matplotlib's pyplot should not be imported at the top-level

### ISSUE THREAD

**Issue by Erotemic** [aleju/imgaug#225]
Importing the pyplot library from matplotlib has unintended side effects at import time. Specifically it causes the matplotlib backend to lock into whatever the current setting is. This (1) makes it difficult to change later using `matplotlib.use`, (2) means that matplotlib must be installed to use `imgaug`, and (3) takes unnecessary time on import that may be better being lazily loaded. 

A lot of libraries make the mistake of importing pyplot at the top level. When this happens (and the developer invariably runs into problems), you will often see them them work around it with a ugly global configuration as such:

```python
import matplotlib
matplotlib.use('agg')
import <module-that-imports-pyplot-at-the-top-level>
```

Not only is this ugly, it is fragile, because now importing whatever the module you are creating will cause the matplotlib backend to be configured and frozen.  

The solution is to simply move all:  `import matplotlib.pyplot as plt` into the functions that use them. This will allow a user to (1) import imgaug without having to absolutely require that matplotlib is installed and (2) avoid having to execute any nasty global configuration code at import time. 

From what I see only two files use pyplot:  [imgaug.py](https://github.com/aleju/imgaug/blob/master/imgaug/imgaug.py) and [parameters.py](https://github.com/aleju/imgaug/blob/master/imgaug/parameters.py), and each of these files only references `plt` 4 times, so it should be an easy fix.

**Comment by aleju** [comment]
Thanks for the suggestion!
This is now in master.
