### ISSUE TITLE
Problem with latest verison of Numpy 1.16.0

### ISSUE THREAD

**Issue by epratheeban** [aleju/imgaug#235]
Hi, 

When importing 

import imgaug as ia 

I get this error 
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imgaug as ia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prat/.local/lib/python3.5/site-packages/imgaug/__init__.py", line 2, in <module>
    from imgaug.imgaug import *
  File "/home/prat/.local/lib/python3.5/site-packages/imgaug/imgaug.py", line 22, in <module>
    import skimage.draw
  File "/home/prat/.local/lib/python3.5/site-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/home/prat/.local/lib/python3.5/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/prat/.local/lib/python3.5/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

```
Also I cant downgrade my numpy. 

Any help please !

TIA

**Comment by aleju** [comment]
Judging from the stacktrace this looks like an issue with scikit-image -- they seem to be trying to import a numpy function that does not exist anymore. Try upgrading scikit-image to the latest version from their repository or see in their issue list whether somebody else had the same problem.
Worst case, you could copy the imgaug code and comment out the line `import skimage.draw` from `imgaug.py`, then install directly from that modified code. But then you can't use most drawing routines in imgaug anymore and I wouldn't be surprised if other imports from scikit-image are going to cause the same issue.

**Comment by aleju** [comment]
Here is the corresponding issue on the scikit-image repository: https://github.com/scikit-image/scikit-image/issues/3586
Looks like they are aware of the problem and try to rush through a hotfix.
The latest build of imgaug on travis also crashed due to this problem.

**Comment by noorkhokhar99** [comment]
try it. solved error.
install it pip install package name.
numpy==1.16.3
scikit-image==0.15.0
keras==2.0.8

**Comment by ziyeshanwai** [comment]
for me ,i solved it by upgrading sckikit-imge to the lastest version
