### ISSUE TITLE
What is the functionality of "seq.to_deterministic()"?

### ISSUE THREAD

**Issue by pengpaiSH** [aleju/imgaug#26]
I notice that in the example of ```README.md```, all examples related with augmenting landmark points have a following line of code. However, it seems that the examples that only augment images do not. 
```seq_det = seq.to_deterministic() # call this for each batch again, NOT only once at the start```
Is it necessary only for landmarks augmentation?

**Comment by aleju** [comment]
`to_deterministic()` removes the randomness from all augmenters and makes them deterministic (e.g. for each parameter that comes from a distribution, it samples one value from that distribution and then keeps reusing that value). That is useful for landmark augmentation, because you want to transform images and their landmarks in the same way, e.g. rotate an image and its landmarks by 30 degrees. If you don't have landmarks, then you most likely don't need the function.

**Comment by pengpaiSH** [comment]
@aleju Thank you for your quick response. Your explanation is very helpful and makes sense. Thank you!

**Comment by george-gssy** [comment]
I think it's worth more documentation.
Thank you,
George

**Comment by SunHaozhe** [comment]
> `to_deterministic()` removes the randomness from all augmenters and makes them deterministic (e.g. for each parameter that comes from a distribution, it samples one value from that distribution and then keeps reusing that value). That is useful for landmark augmentation, because you want to transform images and their landmarks in the same way, e.g. rotate an image and its landmarks by 30 degrees. If you don't have landmarks, then you most likely don't need the function.

Could you please provide some snippet code which shows how `to_deterministic()` should be used to ensure reproducibility?

**Comment by prhbrt** [comment]
> > `to_deterministic()` removes the randomness from all augmenters and makes them deterministic (e.g. for each parameter that comes from a distribution, it samples one value from that distribution and then keeps reusing that value). That is useful for landmark augmentation, because you want to transform images and their landmarks in the same way, e.g. rotate an image and its landmarks by 30 degrees. If you don't have landmarks, then you most likely don't need the function.
> 
> Could you please provide some snippet code which shows how `to_deterministic()` should be used to ensure reproducibility?

An addition to the documentation would be that `seq.to_deterministic(), seq.to_deterministic()` will create two different augmenters. I.e. it's not just for debugging, but also to get locally consistent augmentations.
