### ISSUE TITLE
Feature request: Improve performance for segmentation maps

### ISSUE THREAD

**Issue by jnd77** [aleju/imgaug#264]
Hi.

First, I would like to thank you for the great library. Very user-friendly and full of features. :)

I've noticed the overall process (augmentation of images, bounding boxes and segmentation maps) is spending most of its time on the segmentation maps.
In particular whichever augmenter is used, there is some significant overhead in transforming the seg map into a heat map, and then back to the seg map. Am wondering if it could be improved by doing it only when necessary, as some augmenters have no effect on the seg map (e.g. Add brightness) or could work directly on the seg map (e.g. Flip, Translate) ?

Thanks a lot !

**Comment by aleju** [comment]
Thanks for the praise!
Segmentation map augmentation is currently not exactly the fastest process. It uses heatmap augmentation as a proxy as that method was already implemented and tested. Usually it should convert the segmentation maps to heatmaps exactly once at the start of the pipeline and then convert back once at the end. So if you combine multiple augmenters (e.g. via Sequential) the conversion should only happens once (per augmentation run). Augmenters that don't affect segmentation maps should then not change these heatmaps in any way and not cost noteworthy performance.
Many augmenters could directly operate on the (integer-based) segmentation maps. It is planned to change that in the future, but it will be a rather big change, so it hasn't happened yet (SegmentationMapOnImage needs to be rewritten, various augmenters need new segmentation-map specific augmentation functions, all of these changes then have to be tested and the documentation will have to be updated for some methods).

**Comment by jnd77** [comment]
Thanks. I look forward to it.
I leave the issue open until then ?

**Comment by aleju** [comment]
OK.

**Comment by jnd77** [comment]
Thanks a lot for implementing it ! Much appreciated. :)
