### ISSUE TITLE
can not use weather augmenter 

### ISSUE THREAD

**Issue by cam4ani** [aleju/imgaug#265]
First a big thanks for this great tool!

Do you have any idea why I can't use any of the weather augmenters (with imgaug version '0.2.6')? It always give me an error : "AttributeError: module 'imgaug.augmenters' has no attribute 'X'"

e.g.:
from imgaug import augmenters as iaa
seq = iaa.Sequential([iaa.Snowflakes()])
#AttributeError: module 'imgaug.augmenters' has no attribute 'Snowflakes'

Thank you very much!

**Comment by aleju** [comment]
Any specific reason why you don't update? The weather augmenters were added rather recently. It was either in 0.2.6 or in 0.2.7. As they don't seem to be in your version, I guess it was 0.2.7.

If you can't update, you can probably copy the file augmenters/weather.py. But it has some dependencies that don't exist in 0.2.6, e.g. it uses blend_alpha() from blend.py and blur_gaussian() from blur.py. Also some dtype-related functions from dtypes.py.

**Comment by cam4ani** [comment]
Thank you for your answer. Because I tried but got an error:
....
    OSError: [WinError 126] Le module spécifié est introuvable
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-vhclzeos\Shapely\

Hence I was hoping it was soemthing else.

**Comment by cam4ani** [comment]
Actually I still have some numpy error coming from blend.py:

AttributeError: module 'numpy' has no attribute 'float128'

... hard to find the correct version of all packages that fit together, if anyone have some insights!

**Comment by aleju** [comment]
The first error was due to some problem with Shapely. That was actually not necessary to install, as that library is nowadays an optional dependency.
The second error was due to scikit-image crashing with the newest version of numpy (which is apparently fixed by now).

The problem that you posted should now be fixed in master. For some reason your system doesn't seem to know numpy.float128. Might be a windows thing.

**Comment by cam4ani** [comment]
Thank you for your answer. Might be indeed, I am working under windows.

**Comment by akankshabali5** [comment]
Traceback (most recent call last):

  File "<ipython-input-6-0140440c8630>", line 3, in <module>
    seq = iaa.Sequential([

AttributeError: module 'imgaug.augmenters' has no attribute 'Sequential'


How to resolve this error? pls help
