### ISSUE TITLE
Image Translation

### ISSUE THREAD

**Issue by pGit1** [aleju/imgaug#27]
I am not sure how to ask this question properly so bare with me. 

I am going to **try** to use an illustrative example:

1. Consider a door on its hinges. Lets say door opens away from you (so that you have to push the door open rather than pull it towards you). Picture the door rotating on its hinge away from you, the door nob now appears further away from you, assuming you pushed the door and stayed in the same spot. 

Is there an image translation that does the equivalent of this? So the "door knob" portions of the image would appear further away and the portions of the image closest to the "hinge" would appear closer.

Similar idea to these?
 
![image](https://cloud.githubusercontent.com/assets/13975114/24581154/fe38c16a-16e3-11e7-81f0-114d394a8dc5.png)

I am not looking for a 3d images I am just wanting some portions of my image closer and some portions further away.

**Comment by pGit1** [comment]
Looking at this site I guess I could have simplified this by asking for shearing in the Y direction not just the X. Perhaps this library already does that!

![image](https://cloud.githubusercontent.com/assets/13975114/24581366/e4b428a2-16e7-11e7-941a-5a85862b2f6a.png)

**Comment by aleju** [comment]
What you want sounds like a transformation that moves two corners of the same image side closer together, similar to shear in the images, just applied to two sides at the same time.
I guess the easiest way to achieve that might be [PiecewiseAffineTransform](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.PiecewiseAffineTransform) (see [example](http://scikit-image.org/docs/dev/auto_examples/transform/plot_piecewise_affine.html)), with the original image corners as source points and the new image corners (with two of them closer together) as the target points.

**Comment by pGit1** [comment]
Actually this is an extremely powerful transformation I just did not know
how to begin to describe it. However the transform I describe above seems
much more simple by comparison. Instead of shearing an image in the X
directions I was wondering if there was a way to do it in the Y direction
so an image could be transformed similar to a door opening and closing in
space.

**Comment by aleju** [comment]
You can probably simulate that door effect with PiecewiseAffineTransform. The current `Affine` augmenter has a shear parameter, but that one maps to [AffineTransform's](http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.AffineTransform) shear parameter. Their doc says about it just `Shear angle in counter-clockwise direction as radians`, so not sure if it is x- or y-direction shear.
