### ISSUE TITLE
Numpy version required in `setup.py` does not match `requirements.txt`

### ISSUE THREAD

**Issue by dmsammons** [aleju/imgaug#274]
Specifically, [requirements.txt](https://github.com/aleju/imgaug/blob/master/requirements.txt#L4) requires `numpy>=1.15,<1.16` whereas [setup.py](https://github.com/aleju/imgaug/blob/master/setup.py#L14) requires `numpy>=1.15.0`. This means that `pip install imgaug` will install the latest version of numpy which is greater than 1.16. As noted in issue https://github.com/aleju/imgaug/issues/235, there is a compatibility issue with latest `numpy`/`scikit-image`.

It looks like a fix is coming to make compatible with `numpy>=1.16` in PR https://github.com/aleju/imgaug/pull/267. Until then, should `setup.py` also require `numpy>=1.15,<1.16`?

I can submit a PR to fix this if necessary.

**Comment by aleju** [comment]
numpy 1.16 was only disallowed because of the compatibility issues between numpy and scikit-image. These are afaik fixed now, which is why PR #267 is going to reactivate it again. It will likely be merged today.

**Comment by aleju** [comment]
#267 is now merged, so requirements.txt and setup.py should match again. Thanks for pointing this out, I had completely forgotten about setup.py.

**Comment by dmsammons** [comment]
Thanks for the update.
