### ISSUE TITLE
How can I do batch bounding box augmentation? 

### ISSUE THREAD

**Issue by RiverBridge** [aleju/imgaug#296]
I'm trying to augment the single Quokka image and transfer the bounding box to 5 new augmented images. But my bounding boxes aren't transferring correctly. Could someone please point me in the right direction?

The below code does work. It just doesn't transfer the bounding boxes correctly.  Any help is much appreciated. Thanks for a great library!

````
import imageio
import numpy as np
import imgaug as ia
from imgaug import augmenters as iaa

# How many images do you want to generate from 1 source?
GEN_IMG = 5

ia.seed(1)

singleImage = ia.quokka(size=(256, 256))

images = np.array(
	[singleImage for _ in range(GEN_IMG)], dtype=np.uint8)

bbs = ia.BoundingBoxesOnImage([
    ia.BoundingBox(x1=65, y1=100, x2=200, y2=150),
    ia.BoundingBox(x1=150, y1=80, x2=200, y2=130)
], shape=images.shape)

seq = iaa.Sequential([
    iaa.Fliplr(0.5),
    iaa.Crop(percent=(0, 0.1)), 
    iaa.Sometimes(0.5,
        iaa.GaussianBlur(sigma=(0, 0.5))
    ),
    iaa.ContrastNormalization((0.75, 1.5)),
    iaa.AdditiveGaussianNoise(loc=0, scale=(0.0, 0.05*255), per_channel=0.5),
    iaa.Multiply((0.8, 1.2), per_channel=0.2),
    iaa.Affine(
        scale={"x": (0.8, 1.2), "y": (0.8, 1.2)},
        translate_percent={"x": (-0.2, 0.2), "y": (-0.2, 0.2)},
        rotate=(-25, 25),
        shear=(-8, 8)
    )
], random_order=True) # apply augmenters in random order

for i in range(GEN_IMG):
	try:
		seq_det = seq.to_deterministic()
		bbs_aug = seq_det.augment_bounding_boxes([bbs])[0]
		image_aug = seq_det.augment_images([images[i]])[0]
		image_after = bbs_aug.draw_on_image(image_aug, thickness=2, color=[0, 0, 255])
		imageio.imwrite('/home/pi/imgaug-train/xmlTransferTest/' + str('image_after') + str(i) + '.jpg', image_after)
	except IndexError:
		pass
		
image_before = bbs.draw_on_image(singleImage, thickness=2)
imageio.imwrite('/home/pi/imgaug-train/xmlTransferTest/' + str('image_before') + '.jpg', image_before)

**Comment by aleju** [comment]
> But my bounding boxes aren't transferring correctly.

What do you mean with that?

I see an error in this part:
```python
bbs = ia.BoundingBoxesOnImage([
    ia.BoundingBox(x1=65, y1=100, x2=200, y2=150),
    ia.BoundingBox(x1=150, y1=80, x2=200, y2=130)
], shape=images.shape)
```
`shape=images.shape` needs to be `shape=singleImage.shape` (or `shape=images.shape[1:]`) as these BBs are placed on one image and the bounding boxes require that specific image's shape (here, the shape is always the same).
I think you should also change the bounding box coordinates a bit, as they aren't matching any object in the image and that makes it visually quite hard to judge if the augmented coordinates are actually correct.

**Comment by RiverBridge** [comment]
> > But my bounding boxes aren't transferring correctly.
> 
> What do you mean with that?
> 
> I see an error in this part:
> 
> ```python
> bbs = ia.BoundingBoxesOnImage([
>     ia.BoundingBox(x1=65, y1=100, x2=200, y2=150),
>     ia.BoundingBox(x1=150, y1=80, x2=200, y2=130)
> ], shape=images.shape)
> ```
> 
> `shape=images.shape` needs to be `shape=singleImage.shape` (or `shape=images.shape[1:]`) as these BBs are placed on one image and the bounding boxes require that specific image's shape (here, the shape is always the same).
> I think you should also change the bounding box coordinates a bit, as they aren't matching any object in the image and that makes it visually quite hard to judge if the augmented coordinates are actually correct.

Thank you so much. This fixed my problem. And by "transferring" I meant the "augmented box" was not being transferred to the new augmented images.

I just changed the shape to singleImage and it works perfect. Thanks again.
