### ISSUE TITLE
Cant load augmenters

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#3]
As said in the README, I copied the required files into my directory and ran the 
`from imgaug import augmenters as iaa`

but I get an error 

"ImportError: cannot import name 'augmenters'"

**Comment by aleju** [comment]
Use instead
```python
import augmenters as iaa
```
and if you ever need the parameters, then similarly
```python
import parameters as iap
```

**Comment by SarthakYadav** [comment]
Thanks. This works. But what is the issue with the originally instructed import line?

**Comment by aleju** [comment]
The original import statement was written under assumption that the library has a proper installer (installing it under `imgaug`), but it doesn't have that yet. Didn't notice that problem while testing the examples, will have to change that.

**Comment by SarthakYadav** [comment]
Makes sense. I see the documentation is quite scarce to be precise. I am no expert in Computer Vision, but I am a Deep Learning Researcher. I came across your repo and I realized rather than writing my own routines for Image Augmentation from scratch this can be quite useful. What do you have to say about a contributor to your project?

**Comment by aleju** [comment]
Feel free to contribute if you find anything. And yeah, the documentation needs work as the code/API has currently basically zero documentation, there are just the few examples in the readme.

**Comment by SarthakYadav** [comment]
That's awesome. your preferred Medium for communication?

**Comment by aleju** [comment]
Probably easiest for now to just open issues, then others could theoretically join in.

**Comment by SarthakYadav** [comment]
Ok. Done. 

One final (rather irrelevant) question though that I want to ask right here,

I see that ContrastNormalization has an alpha parameter. What does the alpha parameter do?

**Comment by aleju** [comment]
It controls the strength of contrast, i.e. higher alpha means more contrast. The augmenter currently changes each pixel in an input image independently to the new value `alpha * (i - 128) + 128`, where `i` is the original pixel value.
