### ISSUE TITLE
Import imgaug error

### ISSUE THREAD

**Issue by tianzq** [aleju/imgaug#30]
When I was running "from imgaug import augmenters as iaa"
It has an error:
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

But the libmkl_avx2.so and libmkl_def.so are in the folder ~/anaconda2/lib/.

**Comment by aleju** [comment]
That looks like a problem with your anaconda installation, not with the library.
[Here](http://stackoverflow.com/questions/36659453/intel-mkl-fatal-error-cannot-load-libmkl-avx2-so-or-libmkl-def-so) is a stackoverflow thread that looks like it deals with the same problem.

**Comment by tianzq** [comment]
Great! Follow your @aleju suggestion, the problem is solved!
