### ISSUE TITLE
Random Crop Position of a Fixed Size

### ISSUE THREAD

**Issue by J6767** [aleju/imgaug#31]
Not a bug, a question. 

Is it possible to use the crop function to randomly crop an image to a fixed size? I.e.: crop 256x256 images to 224x224 at a random position (within the image area)? 

Thank you.

**Comment by J6767** [comment]
Thank you, that's great.

**Comment by CWOA** [comment]
The error I get when trying to implement this:
`TypeError: Can't instantiate abstract class FixedCropParameter with abstract methods _draw_samples`
Any ideas?

**Comment by WillBrennan** [comment]
It'd be a good idea to add this to the documentation somewhere.

**Comment by vinojhosan** [comment]
Yes, currently new function has been added as 
iaa.CropToFixedSize(width=224, height=224)
