### ISSUE TITLE
Bug: Polygon error. If number of key point over 118, last point will be missing

### ISSUE THREAD

**Issue by CBCBCBCBCBCBCBCB** [aleju/imgaug#313]
My code is in below, please run my code first and read this simple code description.

I made 'my_list' list object that contains 236 elements.
Elements with odd index mean x coordinate, when even index for y coordinate.
'polygon_list' has 118 tuples which mean 118 keypoints for polygon.
When I made 'my_pol' Polygon object, and print it,
I only has 117 points. Last point that (320,787) was missing.

Did I make mistake?

Thanks.

This is my code,

from imgaug.augmentables.polys import Polygon, PolygonsOnImage

cnt = 0
my_list = [320.0, 787.5, 284.0, 787.5, 260.0, 781.5, 233.0, 779.5, 227.5, 771.0, 228.5, 762.0, 233.5, 756.0, 231.0,
           742.5, 227.0, 747.5, 220.0, 749.5, 210.0, 749.5, 201.0, 743.5, 196.0, 748.5, 181.0, 748.5, 169.0, 744.5,
           148.5, 725.0, 141.5, 707.0, 132.0, 705.5, 122.0, 699.5, 107.5, 680.0, 107.5, 671.0, 115.0, 661.5, 136.0,
           648.5, 152.0, 645.5, 153.5, 638.0, 164.0, 631.5, 176.0, 616.5, 204.5, 593.0, 206.5, 588.0, 203.0, 571.5,
           196.0, 578.5, 187.5, 575.0, 187.5, 571.0, 195.5, 562.0, 195.5, 557.0, 186.0, 545.5, 157.0, 549.5, 149.5,
           542.0, 151.5, 528.0, 144.5, 510.0, 144.5, 493.0, 132.5, 455.0, 129.5, 418.0, 132.5, 374.0, 118.5, 316.0,
           109.5, 298.0, 103.5, 267.0, 97.5, 256.0, 92.5, 235.0, 93.5, 218.0, 110.5, 188.0, 136.0, 163.5, 144.5,
           161.0, 140.0, 159.5, 133.5, 150.0, 134.5, 129.0, 127.0, 126.5, 112.5, 108.0, 112.5, 101.0, 116.5, 95.0,
           115.5, 75.0, 119.5, 70.0, 119.5, 59.0, 146.0, 30.5, 166.0, 22.5, 190.0, 23.5, 215.0, 30.5, 246.5, 65.0,
           247.5, 107.0, 253.5, 124.0, 250.5, 159.0, 244.0, 166.5, 226.0, 173.5, 221.5, 181.0, 232.0, 183.5, 245.5,
           193.0, 272.5, 237.0, 291.5, 257.0, 299.5, 270.0, 303.5, 284.0, 303.5, 304.0, 299.5, 324.0, 291.5, 341.0,
           313.5, 397.0, 324.5, 416.0, 335.5, 428.0, 333.5, 443.0, 322.5, 455.0, 330.5, 491.0, 338.5, 508.0, 337.5,
           516.0, 333.0, 519.5, 324.0, 519.5, 320.5, 529.0, 321.5, 539.0, 330.5, 555.0, 331.5, 571.0, 323.5, 583.0,
           297.5, 605.0, 292.0, 617.5, 270.5, 621.0, 269.5, 634.0, 274.5, 651.0, 269.5, 657.0, 267.5, 672.0, 268.5,
           693.0, 280.5, 727.0, 288.0, 729.5, 296.0, 741.5, 303.0, 741.5, 309.0, 736.5, 317.0, 737.5, 333.0, 755.5,
           341.0, 756.5, 346.5, 763.0, 346.5, 768.0, 339.0, 778.5, 320.0, 787.5]

polygon_list=[]

###################
#loop part
###################
for i in range(int(len(my_list)/2)):
    x = my_list[cnt]
    y = my_list[cnt+1]
    tmp = (int(x), int(y))
    polygon_list.append(tmp)
    cnt+=2
###################

my_pol = Polygon(polygon_list)

print(polygon_list)
print(my_pol)

**Comment by aleju** [comment]
Polygons are in imgaug by definition always closed and hence don't require a last point that is identical to the first point. If the last point is (almost) identical to the first point, it is automatically removed. The e.g. drawing functions will still draw the polygon in closed form.

**Comment by CBCBCBCBCBCBCBCB** [comment]
> Polygons are in imgaug by definition always closed and hence don't require a last point that is identical to the first point. If the last point is (almost) identical to the first point, it is automatically removed. The e.g. drawing functions will still draw the polygon in closed form.

Thanks to reply my question. My problem solved.
