### ISSUE TITLE
Dtype error in some augmentations

### ISSUE THREAD

**Issue by derNorweg** [aleju/imgaug#321]
While using some of the augmentations i get the following error:
Got dtype 'float64' in augmenter 'UnnamedCoarseDropout' (class 'MultiplyElementwise'), which is a forbidden dtype (uint32, uint64, uint128, uint256, int32, int64, int128, int256, float64, float96, float128, float256)

The case is i explicitly convert input data to np.uint8 line before using those augmentations. Also, there are other augmentations, that do not throw exception. All of the cases with errors throw dtype error.

These are throwing an error:
#iaa.Superpixels(p_replace=0.5, n_segments=64),
#iaa.AdditiveGaussianNoise(scale=(0, 0.05*255)),
#iaa.Multiply((0.5, 1.5)),
#iaa.CoarseDropout(0.02, size_percent=0.5),

While these are working perfectly fine:
iaa.Invert(0.5),
iaa.ContrastNormalization((0.5, 1.5)),
iaa.Affine(shear=(-16, 16)),
iaa.Affine(rotate=(-10, 10)),
iaa.PiecewiseAffine(scale=(0.01, 0.03)),
iaa.ElasticTransformation(alpha=(0, 1.0), sigma=0.7)

**Comment by aleju** [comment]
Please post some more code, like e.g. the full pipeline that leads to the error. If you feed in uint8 images the error should not pop up. It could indicate that one of the augmenters converts temporarily to float64 and forgets to convert back to uint8. In that case, the augmenters that throw errors aren't at fault, but one of the seemingly correctly working ones is.

**Comment by derNorweg** [comment]
def augment_it(X_data, transpose=True):
    pad=iaa.CropAndPad(
    percent=(0, 0.2),
    pad_mode=["constant", "edge"],
    pad_cval=(0, 128)
    )

    blur = iaa.OneOf([
    iaa.GaussianBlur(sigma=(0.0,3.0)),
    iaa.AverageBlur(k=(2, 3)),
    iaa.MedianBlur(k=(3, 5))
    ])

    some_of = iaa.SomeOf((0,5), [
    #iaa.Add((np.int8(-40),np.int8(40))),
    iaa.Noop(),
    pad,
    #iaa.Superpixels(p_replace=0.5, n_segments=64),
    #iaa.AdditiveGaussianNoise(scale=(0, 0.05*255)),
    #iaa.Multiply((0.5, 1.5)),
    #iaa.CoarseDropout(0.02, size_percent=0.5),
    iaa.Sharpen(alpha=(0.0, 1.0), lightness=(0.75, 1.5)),
    iaa.Invert(0.5),
    iaa.ContrastNormalization((0.5, 1.5)),
    iaa.Affine(shear=(-16, 16)),
    iaa.Affine(rotate=(-10, 10)),
    iaa.PiecewiseAffine(scale=(0.01, 0.03)),
    iaa.ElasticTransformation(alpha=(0, 1.0), sigma=0.7)
    ])
    
    if transpose:
        X_data.transpose(0,2,1,3)
        augmentation=iaa.Sequential([some_of])
        X_data.transpose(0,2,1,3)
    else:
        augmentation=iaa.Sequential([some_of])
    
    return augmentation(images=X_data)        
#Sequential is used because in previous versions resizing was necessary

def next_batch(self,augmentation=True):       ## batch size만큼 가져오기
    while True:
        X_data = np.ones([self.batch_size, self.img_w, self.img_h, 1])     # (bs, 128, 32, 1)
        Y_data = np.ones([self.batch_size, self.max_text_len])             # (bs, 25)
        input_length = np.ones((self.batch_size, 1)) * (self.img_w // self.downsample_factor - 2)  # (bs, 1)
        label_length = np.zeros((self.batch_size, 1))           # (bs, 1)
        
        for i in range(self.batch_size):
            img, text = self.next_sample()
            img = img.T
            img = np.expand_dims(img, -1)
            X_data[i] = img
            Y_data[i] = text_to_labels(text)

            label_length[i] = len(text)
        
        X_data.astype(np.uint8)
        if augmentation:
                X_data=augment_it(X_data, True)               
        
        X_data = X_data.astype(np.float32)
        X_data=(X_data/127.5)-1

**Comment by aleju** [comment]
Can you try
```python
X_data = X_data.astype(np.uint8)
```
instead of
```python
X_data.astype(np.uint8)
```
`astype()` doesn't work in-place, unless you use the `copy` argument (and then its still not guaranteed).

**Comment by derNorweg** [comment]
I'm really sorry for taking Your time. That's exactly the case.

**Comment by lihua8848** [comment]
From uint64 to uint8 will loss some information, how to solve this problem?
