### ISSUE TITLE
How to save every sample in 'examples_grid.jpg' into separate image?

### ISSUE THREAD

**Issue by panovr** [aleju/imgaug#34]
Currently the `generate_example_images.py' script only generates an ' examples_grid.jpg' image. May I ask that how to save every sample in this grid image into separate image?
Thanks!

**Comment by aleju** [comment]
In the file `generate_example_images.py`, replace in in function `draw_single_sequential_images()` the code
```python
grid = seq.draw_grid(image, cols=8, rows=8)
misc.imsave("examples_grid.jpg", grid)
```
with something like
```python
n = 64
images_aug = seq.augment_images([image] * n)
for i, image_aug in enumerate(images_aug):
    misc.imsave("examples_grid_%04d.jpg" % (i,), image_aug)
```
That should generate and save 64 augmented images (not tested).

**Comment by panovr** [comment]
I can validate that this code works. Thanks!
