### ISSUE TITLE
Error when applying snowflake to image

### ISSUE THREAD

**Issue by EricThomson** [aleju/imgaug#341]
I have a greyscale image (`image.shape` returns `(330,228)` with dtype `uint8`). 
I try the following:
```
snowflakes = iaa.Snowflakes(flake_size = (0.1, 0.4), speed = (0.01, 0.05))
image_sf = snowflakes.augment_image(image)
```
And receive the following error with the second line:

>   File "<ipython-input-71-bea75e84833a>", line 1, in <module>
>     image_sf = snowflakes.augment_image(image)
> 
>   File "/home/eric/miniconda3/envs/auger/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 470, in augment_image
>     return self.augment_images([image], hooks=hooks)[0]
> 
>   File "/home/eric/miniconda3/envs/auger/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 639, in augment_images
>     images_result[i] = np.squeeze(images_result[i], axis=2)
> 
>   File "/home/eric/miniconda3/envs/auger/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1388, in squeeze
>     return squeeze(axis=axis)
> 
> ValueError: cannot select an axis to squeeze out which has size not equal to one

I am in Python 3.7, imgaug 0.2.9, Ubuntu 18.

The other augmenters I have tried have worked fine on the image (e.g., GaussianBlur, MotionBlur, Affine, CoarseDropout).

**Comment by aleju** [comment]
This should now be fixed in master. Thanks for reporting it!
