### ISSUE TITLE
Returning labels

### ISSUE THREAD

**Issue by Doggus** [aleju/imgaug#344]
Hi there, just discovered this library and have been loving it so far. There is one bit of functionality that I cant seem to find anywhere in the documention though. Is it at all possible to return a list of the image labels of a group of augmented images?

For instance I've been loading images from MNIST to train my classifier and have two seperate lists containing my images (numpy arrays) and their labels. Ideally I would like to make an augmentation function to return a new list of augmented images as well as new list containing their labels.

Is this currently possible? or do you intend on ever adding this functionality.

**Comment by aleju** [comment]
I'm a bit confused. Why do you want to feed the labels through the augmentation function? The class labels shouldn't change, so you can just use your original label list without any modification. Only if you feed in `Batch` objects and use unordered background (i.e. multicore) augmentation you would have to make use of the `Batch.data` attribute to save e.g. identifiers or class labels.

**Comment by Doggus** [comment]
Ya so this was a stupid error on my part. For some reason I was under the impression that the sequential function applied each augmentation individually on an array of images i.e creating a new array larger than the original. Working the whole day obviously put a toll on my logic. I realised my mistake the next morning. Thanks for the reply and sorry for wasting your time

**Comment by aleju** [comment]
sure, np :smile: misunderstandings happen all the time
