### ISSUE TITLE
Find Out Transformation Matrix

### ISSUE THREAD

**Issue by r0f1** [aleju/imgaug#360]
Hi,
I have the following list of transformers:
```
    a = [
        iaa.Noop(),
        iaa.Affine(rotate=90),
        iaa.Affine(rotate=180),
        iaa.Affine(rotate=270),
        iaa.Fliplr(1),
        iaa.Flipud(1)
    ]
```
Is there a way to get the transformatition matrices out of all of these transformers?
[I see that there is a parameter for it](https://github.com/aleju/imgaug/blob/c55742d019423602b7b6e47efe146f8bdf59a6bc/imgaug/augmenters/geometric.py#L624
), but I am not sure how to use it.

**Comment by aleju** [comment]
That is currently not part of the library. The `return_matrices` parameter is intended for operations internal to `Affine`. You could however hack it into `Affine` by subclassing it and overwriting `_augment_images_by_samples()`. Something like the following might work:
```python
class TrackedAffine(Affine):
    def _augment_images_by_samples(self, images, scale_samples, translate_samples, rotate_samples, shear_samples, cval_samples, mode_samples, order_samples, return_matrices=False):
        result = super()._augment_images_by_samples(images, scale_samples, translate_samples, rotate_samples, shear_samples, cval_samples, mode_samples, order_samples, return_matrices=True)
        self.last_matrices = None
        if return_matrices:
            self.last_matrices = result[-1]
            return result
        return result[0]
```
Then each instance of `TrackedAffine` should save the last generated matrices in `.last_matrices`.

Though if you only use `Affine` with fixed rotation values as in your code example, you could also pregenerate the matrices yourself as they are never going to change.

**Comment by r0f1** [comment]
Thanks for the detailed answer :)
