### ISSUE TITLE
Possible to pass your own arguments to lambda function

### ISSUE THREAD

**Issue by Doggus** [aleju/imgaug#363]
Hi there, so ive been adding my own custom functions as a lambda function so they can be used with Sequential. Its been working so far but recently I've attempted to pass my own arguments for the function to use but I just cant figure out how to do this. I looked at the examples in the docs and cant see any instance of passing your own arguments. Is this currently possible?

Example of my code is below:

```
def Edges(images, random_state, parents, hooks, min, max):

        new_imgs = []

        for img in images:

            # convert images to greyscale
            grey_img = np.array(Image.fromarray(img).convert('L'))
            # extract edges from image
            edges = cv2.Canny(grey_img, min, max)
            # add images to list
            new_imgs.append(edges)

        # Convert list to numpy array
        aug_imgs = np.asarray(new_imgs)
        return aug_imgs

aug = iaa.Lambda(func_images=Edges)
```

how would you enter values for min and max here?

**Comment by aleju** [comment]
Are these values static? The cleanest solution is probably a class then:
```python
class Edges:
    def __init__(self, min_value, max_value):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, images, random_state, parents, hooks):
        new_imgs = []

        for img in images:

            # convert images to greyscale
            grey_img = np.array(Image.fromarray(img).convert('L'))
            # extract edges from image
            edges = cv2.Canny(grey_img, self.min_value, self.max_value)
            # add images to list
            new_imgs.append(edges)

        # Convert list to numpy array
        aug_imgs = np.asarray(new_imgs)
        return aug_imgs

aug = iaa.Lambda(func_images=Edges(min_value=0.2, max_value=0.3))
```
That should usually work.

Btw, there is a `Canny` augmenter in the latest version of master in `imgaug.augmenters.edges.Canny`, though not documented in ReadTheDocs yet.

**Comment by Doggus** [comment]
Alright thanks for the answer. Had no idea it was already in the library. Will probably just use that then.
