### ISSUE TITLE
Wrong bounding box

### ISSUE THREAD

**Issue by fabiofumarola** [aleju/imgaug#372]
I have made a simple example to check how the bounding box is performed when Resizing an image. I've found that the box on the target image is wrong with respect the original one.

### Original Image
![original image](https://user-images.githubusercontent.com/1550672/61950855-7d6ddb80-afaf-11e9-8534-44dfe06c12ba.png)

### Scaled image with imgaug
![scaled_image_imgaug](https://user-images.githubusercontent.com/1550672/61950860-83fc5300-afaf-11e9-817e-73cb71b25f6f.png)

```
import imgaug as ia
import imgaug.augmenters as iaa
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage

bbs = BoundingBoxesOnImage([BoundingBox(*box) for box in updated_boxes], shape=img.shape)
seq = iaa.Sequential([iaa.Resize(target_shape)])

mod_img_2, updated_boxes_2 = seq(image=img, bounding_boxes=bbs)

ax = utils.show_img(mod_img_2)
for box in updated_boxes_2.bounding_boxes:
    utils.draw_rect(ax, [box.x1_int, box.y1_int, box.x2_int, box.y2_int])
plt.show()
```

### Right scaled image
![right_scaled_image](https://user-images.githubusercontent.com/1550672/61950879-8c548e00-afaf-11e9-9491-a265771c48e9.png)

```
input_h, input_w = input_shape
target_h, target_w = target_shape
scale_w = target_w / input_w
scale_h = target_h / input_h
print(scale_w, scale_h)

updated_boxes2 = boxes.copy()
updated_boxes2[:, [0, 2]] = updated_boxes2[:, [0, 2]] * scale_w
updated_boxes2[:, [1, 3]] = updated_boxes2[:, [1, 3]] * scale_h
updated_boxes2[updated_boxes2 < 0] = 0
updated_boxes2
```

**Comment by aleju** [comment]
Hm, can you maybe extend the example code a bit so that it is more reproducible? I tried to modify it to the below version, but the output looks fine for me, so there must be something different in your local code. Particularly, `target_shape`, `updated_boxes` and the exact image dimensions are not specified.

```python
import numpy as np
import imgaug as ia
import imgaug.augmenters as iaa
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage

img = ia.quokka_square((256, 300))
target_shape = {"height": 256, "width": 200}
updated_boxes = [
    {"x1": 5, "x2": 110, "y1": 70, "y2": 250},
    {"x1": 100, "x2": 250, "y1": 50, "y2": 250}
]

bbs = BoundingBoxesOnImage([BoundingBox(**box) for box in updated_boxes], shape=img.shape)
seq = iaa.Sequential([iaa.Resize(target_shape)])

mod_img_2, updated_boxes_2 = seq(image=img, bounding_boxes=bbs)

before = bbs.draw_on_image(img, size=3)
after = updated_boxes_2.draw_on_image(mod_img_2, size=3)
spacer = np.full((before.shape[0], 10, 3), 255, dtype=np.uint8)

ia.imshow(np.hstack([before, spacer, after]))
```

![issue372](https://user-images.githubusercontent.com/11698516/61962381-a4d1a200-afc9-11e9-9b3f-41475ddb6c95.png)

**Comment by shaofengzeng** [comment]
Affine function has the same problem

**Comment by fabiofumarola** [comment]
I have checked the code and there was a bug in my code. 
Thanks
