### ISSUE TITLE
The format of the output image

### ISSUE THREAD

**Issue by WallZFE** [aleju/imgaug#373]
Hello,Thank you for providing such good code.I have a question now,I wonder if the format of the converted image is RGB or BGR,Because I need to read it in opencv format.Please let me know if you know. Thank you

**Comment by aleju** [comment]
imgaug usually expects images to be in RGB, but I think all augmenters that deal with colors offer parameters to change the colorspace. Look out for something like `from_colorspace=...`.

If you don't want to fiddle with those parameters you can also temporarily explicitly change the colorspace, e.g. the following should work:
```python
import imgaug.augmenters as iaa

children = [
    iaa.Affine(...),
    iaa.AdditiveGaussianNoise(...),
    iaa.AddToHue(...)
]   # example augmenters

# execute children, but convert first from BGR to RGB,
# then convert back to BGR at the end
sequence = iaa.WithColorspace(
    "RGB", from_colorspace="BGR", children=children)

images_bgr_aug = sequence(images=images_bgr)
```

**Comment by WallZFE** [comment]
I really appreciate your reply，I'll try your way，Thanks
