### ISSUE TITLE
Question: augmentor parallelism

### ISSUE THREAD

**Issue by Doggus** [aleju/imgaug#378]
Hi there. Love the library. Just wanted to ask a quick question. I'm curious to know if you have used parallelism in any way to speed up the augmentation process and if so is there any way at all to manipulate or turn off said parallelism (e.g. run augs on one thread, choose how many threads to use, etc). Thanks and have a great day.

**Comment by aleju** [comment]
imgaug has some capability to run augmentation pipelines on multiple CPU cores in a reproducible way. See the [multicore notebook](https://nbviewer.jupyter.org/github/aleju/imgaug-doc/blob/master/notebooks/A03%20-%20Multicore%20Augmentation.ipynb) for details on that.
imgaug uses OpenCV for some methods, which may or may not use multi-threading. You can deactivate that using `cv2.setNumThreads(0)`.

**Comment by Doggus** [comment]
Alright awesome. Just the imnformation I wanted to know. Thanks a bunch

**Comment by Doggus** [comment]
Actually one last thing
