### ISSUE TITLE
Bounding Boxes: Filter Support

### ISSUE THREAD

**Issue by MentalGear** [aleju/imgaug#390]
First off, thanks for this nice plugin and the mostly great documentation. However, when I was going through some filters with a dataset that has bounding boxes, I noticed that for some filters, the bounding boxes disappaer for the augmented images.

Is there a list somewhere which indicates what filters are safe and keep bounding boxes, or is there any other way to identify filters that don't return labels ?

**Comment by aleju** [comment]
Which augmenters did you use and how did you call them? As far as I recall, there is no augmenter that removes bounding boxes. They might be augmented so much that their coordinates end up outside of the image plane, but nevertheless they should not be removed. If they are, that would most likely be a bug.

**Comment by MentalGear** [comment]
Mh, must have been some bug on colab. Seems to work now, sorry for the issue, closing it now !
