### ISSUE TITLE
bgr image preprocess problem

### ISSUE THREAD

**Issue by as754770178** [aleju/imgaug#391]
I use cv2 read the image, but after use the function of  `imgaug` preprocess the image. I think the image auto become to `rgb` channel. How to use `imgaug` preprocess the `bgr` image?

**Comment by aleju** [comment]
You can
* Manually convert the colorspace to RGB, e.g. using `cv2.cvtColor(images, cv2.COLOR_BGR2RGB)`.
* Add the argument `from_colorspace="BGR"` when initializing color-based augmenters. All augmenters dealing with colorspaces should support that in their constructors.
* Wrap your pipeline in a `WithColorspace`, e.g. `aug = WithColorspace(from_colorspace="BGR", to_colorspace="RGB", children=Sequential(...))`.

**Comment by as754770178** [comment]
If I do this, the image colorspace is RGB or BGR? I want the image colorspace is BGR after augmentation.

**Comment by aleju** [comment]
If you convert it initially via `cv2.cvtColor`, you have to manually convert back after augmentation via `cv2.cvtColor(images, cv2.COLOR_RGB2BGR)`. The other two options produce BGR images.

**Comment by as754770178** [comment]
Thanks
