### ISSUE TITLE
Explanation of Affine Transforms

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#4]
How does the Affine Transformation works?
What I mean to ask is, out of the selected batch, upon transforming the image batch with the transformer, 
are there non-transformed images in the resulting batch or has every sample obtained certainly gone under some transformation?
LIke, I know the Flip transformers only transform specified ratio of images. What about other transformers?

**Comment by aleju** [comment]
The affine class will sample values for scale (x, y), translation in pixels (x, y), rotation and shear (per image). If any of the scale values is unequal to `1.0` or any of the other values is unequal to `0`, it will transform the image via scikit-image's transform.warp function. So in typical use cases (where each of these values is a range, e.g. rotate by -45° to +45°) it will basically always transform the images. If that is undesired, the class `Sometimes` can be used to only sometimes apply the augmenter. The flip transformers are currently the only ones that have that "sometimes" capability already built into the class, as there is hardly any use case for them without that.

**Comment by SarthakYadav** [comment]
Thanks!! It's crystal clear now.
