### ISSUE TITLE
What is the principle of elastic deformation implement of key points?

### ISSUE THREAD

**Issue by hhaAndroid** [aleju/imgaug#425]
I looked at the code, but I don’t know what the principle is.
1. kp_neighborhood = kp.generate_similar_points_manhattan(
                        self.NB_NEIGHBOURING_KEYPOINTS,
                        self.NEIGHBOURING_KEYPOINTS_DISTANCE,
                        return_array=True
                    )
2. xxyy_aug[:, 0] += dx[yy, xx] 
    xxyy_aug[:, 1] += dy[yy, xx]
3.med = ia.compute_geometric_median(xxyy_aug)

Is this an approximation algorithm?

**Comment by aleju** [comment]
For each augmented keypoint to augment `ElasticTransformation` does the following:
1. Generate a few neighbouring points
2. Shifts all of these points according to each point's local shiftmap and shift strength
3. Compute the geometric median of the all shifted points
4. Use that median as the new (i.e. augmented) point.

This is motivated by keypoints usually denoting the centers of larger structures in the image, so even if that center pixel moves a lot according to the shift map, it might be sensible to actually not move the keypoint if all the other pixels of the structure aren't moving. E.g. if a keypoint denotes the center of a human eye and that center pixel is shifted towards the bottom right of the image, but all the other pixels of the eye are moved to the top left, then you likely want the keypoint to move to the top left and not the bottom right. This is important for `ElasticTransformation`, as the shift map can become very noisy between neighbouring pixels when `sigma` approaches `0`.

There are additionally some heuristics to sometimes avoid keypoint augmentation altogether, mainly if the `sigma` value is very low (i.e. the shift maps are just random noise that is uncorrelated between neighbouring pixels).

**Comment by hhaAndroid** [comment]
thank you
