### ISSUE TITLE
Augmenting dimension size 0 raises SIGSEGV or returns dimension size 512

### ISSUE THREAD

**Issue by rugheid** [aleju/imgaug#430]
When I run the following code:
```python
import imgaug
import numpy

augmentation = imgaug.augmenters.Sequential([
    imgaug.augmenters.Affine(rotate=(-90.0, 90.0)),
])
det = augmentation.to_deterministic()


mask = numpy.zeros((1024, 1024, 0), dtype=numpy.uint8)
augmented = det.augment_image(mask)
print(mask.shape, augmented.shape)
```
It prints `(1024, 1024, 0) (1024, 1024, 512)` or raises a `SIGSEGV` error. I know passing a numpy array with shape size 0 is weird, but it's handy to support it when using images without any instances.

**Comment by aleju** [comment]
Yes, a segmentation fault should definitely not happen there. I guess OpenCV fails for such inputs. I will fix that as soon as possible.

**Comment by rugheid** [comment]
Ok, perfect. Thanks a lot. 😀

**Comment by aleju** [comment]
Most of the augmenters in master should now work with array axis having a size of 0. Some helper functions (e.g. for drawing) will probably still crash. It is also currently only tested for image data, so e.g. segmentation maps on such images might still cause issues.

**Comment by rugheid** [comment]
Quite a big PR you created there! Thanks a lot for fixes the issues so fast. 😀👍🎉
