### ISSUE TITLE
Rot90 in all 4 possible rotations, k=imgaug.ALL gives error

### ISSUE THREAD

**Issue by sbj028** [aleju/imgaug#434]
Considering the documentation for:
 _imgaug.augmenters.geometric.Rot90(k, keep_size=True, name=None, deterministic=False, random_state=None)_

**k** is defined to be an int, list of int, tuple of int or imgaug.ALL, where imgaug.ALL, then equivalant to list [0, 1, 2, 3]. 
Since I'm interested in all four possible rotations I try with k = imgaug.ALL but receive the following error: 

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-community/150/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/150/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../test_lib_imgaug.py", line 18, in <module>
    rotate = iaa.geometric.Rot90(k=imgaug.ALL, keep_size=True, name=None, deterministic=False, random_state=None)
  File ".../lib/python3.6/site-packages/imgaug/augmenters/geometric.py", line 3138, in __init__
    allow_floats=False)
  File ".../lib/python3.6/site-packages/imgaug/parameters.py", line 98, in handle_discrete_param
    name, "number" if allow_floats else "integer", [type(v) for v in param],))
  File .../lib/python3.6/site-packages/imgaug/imgaug.py", line 1869, in do_assert
    raise AssertionError(str(message))
AssertionError: Expected iterable parameter 'k' to only contain integer, got [<class 'str'>, <class 'str'>, <class 'str'>].

It seems like it's not possible to use k=imgaug.ALL as an argument? Or could you please explain how to be able to retrieve all 4 rotations.

**Comment by aleju** [comment]
Yes, the docstring and actual implementation are not in sync there.
To get all rotations use ``Rot90((0, 3))`` or ``Rot90([0, 1, 2, 3])``.

**Comment by sbj028** [comment]
Using Rot90((0, 3)) or Rot90([0, 1, 2, 3]) only return one of the rotations, not all four.  So far, looping through all four indices, one at the time, seems to be the solution.

**Comment by aleju** [comment]
`Rot90` now supports `imgaug.ALL` in master.

But if your goal is to get for each image always all four possible rotations, then a loop is still your best choice as the library is not really made for that use case. Though you can then feed all images through the augmenter in each iteration, so its only four calls, independent of the number of images.

**Comment by sbj028** [comment]
Okey,  then I go for that. Thanks for the update!
