### ISSUE TITLE
Is this a mistake in the tutorial?

### ISSUE THREAD

**Issue by off99555** [aleju/imgaug#494]
![image](https://user-images.githubusercontent.com/15215732/68754441-417f8480-0639-11ea-880a-ceceff02ee2f.png)
Should this be `kpsoi.shape` ?

https://nbviewer.jupyter.org/github/aleju/imgaug-doc/blob/master/notebooks/B01%20-%20Augment%20Keypoints.ipynb

**Comment by aleju** [comment]
Yes, that looks wrong. Will have to change that.
