### ISSUE TITLE
iap.Uniform with translate_px causes translation well beyond specified limits 

### ISSUE THREAD

**Issue by soswow** [aleju/imgaug#505]
Here is an example of a problem:
https://colab.research.google.com/drive/1OM--s8zhyesrzugQxWvHdWRiawko8odx

```python
seq = iaa.Sequential([
    iaa.Affine(
      translate_px=iap.Uniform(-100, 100) # BUG!
      # translate_px=(-100, 100) # Works fine
    ),
])

bbs = BoundingBoxesOnImage([
  BoundingBox(x1=200, x2=400, y1=200, y2=400)
], shape=img.shape)

imgs, bbois = seq(images=[img], bounding_boxes=[bbs])
```
Using this code ^ the resulting translation is massive. It's in hundreds of thousands when  I use Uniform instead of defining `translate_px` as just a tuple.

**Comment by aleju** [comment]
Yes, that seems wrong. You can use `iap.DiscreteUniform` instead of `iap.Uniform` until its fixed. `Affine` then understands that an absolute pixel amount is meant and not a relative amount.
