### ISSUE TITLE
iaa.Affine translate_px applies same number for x and y

### ISSUE THREAD

**Issue by soswow** [aleju/imgaug#507]
Something like this:
```python
seq = iaa.Sequential([
      iaa.Affine(
          translate_px=(-500, 500)
      ),
  ])
```
Seems to be producing augmentation with x and y having same sign. Specifically I can see visually that augmentation either moves bounding boxes up left or right bottom. Which I think means it uses same number for x and y modification. They are always seems to be on the same diagonal, which means x and y translation number is the same.

I can come up with simple reproduce code if needed if it's something to do with my setup.

This is how it looks for me:
<img width="815" alt="Screen Shot 2019-11-28 at 6 39 58 PM" src="https://user-images.githubusercontent.com/108065/69786787-3159ce80-120f-11ea-9023-3f45d8df51a8.png">
<img width="812" alt="Screen Shot 2019-11-28 at 6 39 21 PM" src="https://user-images.githubusercontent.com/108065/69786789-31f26500-120f-11ea-953e-4d4f9043e6bf.png">
<img width="815" alt="Screen Shot 2019-11-28 at 6 38 58 PM" src="https://user-images.githubusercontent.com/108065/69786790-31f26500-120f-11ea-8f5c-13ca13519b8c.png">
(they all start in the middle)

The expected behaviour would be to randomly move it around +- number I say.

**Comment by soswow** [comment]
I can see you have it in the documentation:
> That number will be used identically for both x- and y-axis.

Does this mean this reported bug is actually a feature? If so, I would like to understand what is the benefit of moving image on a diagonal? 🤔This doesn't make sense to me. Maybe I am missing something?

**Comment by soswow** [comment]
oh. I found:

>  If a dictionary, then it is expected to have the keys x and/or y. Each of these keys can have the same values as described above. **Using a dictionary allows to set different values for the two axis and sampling will then happen independently per axis**, resulting in samples that differ between the axes.

**Comment by soswow** [comment]
Ok. I am closing this issue, since it's not an issue. The lesson here could be discoverability and what are the best defaults for these variations.
Thank you.

**Comment by aleju** [comment]
Yes, this will probably be changed in the future so that `translate_px=(-500, 500)` uses different samples per axis (and some other way will allow to use the same samples for both axes). The current interface is quite error-prone and a bit verbose.
