### ISSUE TITLE
Same distortions for all images in a batch

### ISSUE THREAD

**Issue by halwai** [aleju/imgaug#51]
Suppose I have video-frames and I would like to apply same distortions/transformation/augmentations to all the frames while passing them in a single batch(and then other batch with other parameters for the same transformation set). How can this be done?
I am sorry if my query seems to be too naive

**Comment by aleju** [comment]
The easiest way to do that would be to use determinism, something similar to the following:
```python
augseq = iaa.Sequential(iaa.Multiply((0.8, 1.2)))
for batch in batches:
    augseq_det = augseq.to_deterministic()
    frames_aug = [augseq_det.augment_image(frame) for frame in batch.frames]
    train_on_frames(frames_aug)
```
i.e. you make your augmentation sequence deterministic per batch and then apply it to each frame individually.
