### ISSUE TITLE
Affine: Translation question

### ISSUE THREAD

**Issue by r0f1** [aleju/imgaug#511]
Hi,
Is the `translate_percent` parameter of the `Affine` class really in percent? It seems that the whole transformation is really sensitive to this single parameter.  And another question: In which order to you apply the transformations? Do you first rotate and then translate, or first translate and then rotate? 
Thank you.

**Comment by aleju** [comment]
The `translate_percent` parameter is actually a fraction, i.e. its sensible value range is `[-1.0, 1.0]` to translate between -100% and 100% of the image size.

It first rotates and then translates.
Example:
```python
import imgaug as ia
import imgaug.augmenters as iaa

image = ia.quokka_square((100, 100))
image = iaa.pad(image, top=50, right=50, bottom=50, left=50,
                cval=128)

image_translate_and_rotate = iaa.Affine(
    translate_px={"x": 45}, rotate=45
)(image=image)

image_rotate_then_translate = iaa.Sequential([
    iaa.Affine(rotate=45),
    iaa.Affine(translate_px={"x": 50})
])(image=image)

image_translate_then_rotate = iaa.Sequential([
    iaa.Affine(translate_px={"x": 50}),
    iaa.Affine(rotate=45)
])(image=image)

ia.imshow(ia.draw_grid([
    image,
    image_translate_and_rotate,
    image_rotate_then_translate,
    image_translate_then_rotate
], cols=4))
```

![imgaug imshow((200,_800,_3))](https://user-images.githubusercontent.com/11698516/69900835-a7c61000-1378-11ea-8009-ba8891de8597.png)

**Comment by r0f1** [comment]
Thank you, that clarifies things :)
