### ISSUE TITLE
Dropout Applied Per Channel When per_channel=False

### ISSUE THREAD

**Issue by gcmurray** [aleju/imgaug#520]
Hello,

I am trying to use Dropout augmentation on images for training a model, and I can't seem to get it to work per image so as to "black out" pixels. Instead, I'm getting pixels being dropped out per channel, even though per_channel=False. ~~Looking at the code, and comparing it with [this fork, line 4925](https://github.com/abnera/imgaug/blob/master/imgaug/augmenters.py) it seems like the PyPI package version 0.3.0 isn't applying the samples to every channel in a tiled fashion.~~ Presenting images as a batch seems to be the requirement to have it work properly. I am using a picture that starts as grayscale, and is converted to RGB. Here is example code:
```
from imgaug import augmenters as iaa
import skimage
import skimage.io

def augmentation_protocol(mode):
	
	if mode in ['val']:
		aug = iaa.Dropout(p=(0.15,0.20), per_channel=False)   
		
		return aug
	
	if mode in ['train']:
		return None
	
	return None

def main():
	import matplotlib
	matplotlib.use('Qt4Agg')
	import matplotlib.pyplot as plt
	import matplotlib.image as mpimg
	
	img = mpimg.imread("grayimage.jpg", format='jpg')
	if img.ndim != 3:
		img = skimage.color.gray2rgb(img)
	if img.shape[-1] == 4:
		img = img[..., :3]
	aug = augmentation_protocol('val')
	aug_img = aug(images=img)
	
	imgplot = plt.imshow(aug_img)
	#imgplot = plt.imshow(img)
	plt.show()
	
	
if __name__ == "__main__":
	main()
```
Is this an untracked bug, and if so, can we find a way around this? I've attempted to apply a sequential augmentation, converting to gray colorspace then applying dropout, then back to RGB, however this is an exception due to the colorspace augmentation not allowing conversion from GRAY to RGB.

*Workaround / proper procedure*
Be sure to present your images in a list.
```     ...
	aug_img = aug(images=[img])
	imgplot = plt.imshow(aug_img[0])
        ...
```

**Comment by gcmurray** [comment]
I think I've tracked it down to this line in [arithmetic.py, multiply_elementwise function](https://github.com/aleju/imgaug/blob/c268d368f9caeb46d8df4fe73f8f7c988c97dcba/imgaug/augmenters/arithmetic.py#L570). It says TODO, do shape check, and yes, I think that needs to happen. Unfortunately, the hack from [_augment_batch in class MultiplyElementwise](https://github.com/aleju/imgaug/blob/master/imgaug/augmenters/arithmetic.py#L2017) which converts mul type to bool to make Dropout and CoarseDropout perform better seems to break them if they have more than one channel, since the bool check in `multiply_elementwise` goes straight to `image *= multipliers` .. I'm not a math expert but I think this isn't what should happen.

**Comment by gcmurray** [comment]
After reading the doc-strings in the `meta` file, the solution to my particular problem (per_channel=False allowing per channel effects) is to present the image file as a list `[img]` and then read it as the ith element of the list. Presenting it this way makes use of the `augment_batch` correctly, I think, and avoids the use of `augment_image`. It must come down to how the image dimensions are interpreted. Again, I don't know if this is a bug or a feature, but this is how to make sure it works properly.

**Comment by gcmurray** [comment]
Holy smokes, this repository has changed so much and is so different from the PyPI package that this whole question is irrelevant.

**Comment by aleju** [comment]
This is actually just a simple (but very common and confusing) typo.
You wrote
```python
aug_img = aug(images=img)
```
but it has to be either
```python
aug_img = aug(image=img)
```
or 
```python
aug_img = aug(images=[img])[0]
```
Otherwise the library will augment `H` different "grayscale" images of shape `WxC` (where `H` is the image height, `W` is the width and `C=1` is the number of channels) and return again a single `HxWxC` numpy array.
There is already a warning shown in case of `C=3` for RGB images, but not yet one for `C=1`, which allowed that to slip through here.

**Comment by aleju** [comment]
And the repository changed a lot since 0.3.0, but I think for dropout and the underlying functions that was just refactorings to make pylint happy, as well as an internal change to augment batch-wise instead of input-wise (images, keypoints, bounding boxes, etc.).

**Comment by gcmurray** [comment]
Thanks for following up. I'm using imgaug in a project for a conference paper (hopefully) and it's been really useful. I've cloned the repository and "-e" pip installed it to keep up with all the improvements. I appreciate your useful contribution. Keep it up!
