### ISSUE TITLE
Generalization : `np.uint8, [0-255]` -> any dtype, range 

### ISSUE THREAD

**Issue by vfdev-5** [aleju/imgaug#53]
Hi,

Is it difficult to generalize image augmentations without the restrictions of `np.uint8` and 0-255 ?
I saw in the code that there are some augmentations that have a hard-coded np.clip and astype `np.uint8`. 
I started locally to modify test.py to launch tests on float32 data, however tests are not exaustive...
I'm interested in this feature and can help with implementation.

**Comment by aleju** [comment]
The library is currently mainly aimed at uint8 images. Some augmenters probably work with other datatypes, but there isn't a thorough list for these. I would have to go through each augmenter individually to see if it works and whether it is possible to remove clip and astype commands (or, more likely, to use these only if the input dtype was uint8). For some augmenters it will definitely not be possible (e.g. Scale and Grayscale).

**Comment by vfdev-5** [comment]
Okay, I see.  I am trying to understand better what is under the hood of your library. Could you explain, please, what is the purpose of HooksImages? In your README example `activator` allows to skip some augmenters. In `test.py` seems that `propagator` is doing the same, however it is not used in method `Augmenter.augment_images`.  So, one use-case to skip some of augmenters, as I can imagine, could be when switching between train/validation/test phases (personnaly I would define 3 different sequences). Another use-case I see, for example, during image and mask augmentation skip color augmentations on mask transformations. 
Attributes `preprocessor` and `postprocessor` as I understand can be used to preprocess or postprocess image during augmentation, can you give a use-case, please?

**Comment by aleju** [comment]
`activator` defines whether an augmenter may be executed or not. `propagator` defines whether an augmenter may call its children or not. So the activator may allow an augmenter to perform its augmentations, but the propagator may then forbid to additionally call the children. Currently there is no real need for these to be separate, as every augmenter that has children doesn't do any augmentations on its own (e.g. Sequential only executes a list of child augmenters one after the other).
`preprocessor` and `postprocessor` are executed per augmenter before/after modifying the images. Maybe they could be used to log which changes a specific augmenter has performed. So far I have personally never needed them.
The main use case of the hooks in general is currently to use the `activator`. This is specifically useful when you need to augment sets of images in the same way, but also have to avoid using some augmenters for specific sets. Example: Augmenting images and corresponding heatmaps (labels/annotations). You want the images and heatmaps to both be affected in the same way by e.g. `Affine` (e.g. same rotations), but you don't want gaussian noise or dropout to be applied to the heatmaps.
For train/validation/test it is indeed intended to use 3 different sequences.

**Comment by amirbar** [comment]
@vfdev-5 
I made a small modification in a fork and validated it works for few basic features (translation, crop, rotations)..
You can check it out -
https://github.com/amirbar/imgaug
