### ISSUE TITLE
I want aug img to specific num

### ISSUE THREAD

**Issue by Usernamezhx** [aleju/imgaug#533]
first of all. thanks for your work.

def process_folder(path, want_num=500):
    all_files = [os.path.join(path, item) for item in os.listdir(path) if not item.startswith('.')]
    if len(all_files) >= want_num:
        return

    num_iter = math.ceil(want_num * 1.0 / len(all_files))

    block_list = split_list(all_files, num_work)
    block_img = get_block_img(block_list)
    print('read all img ok')

    batches = [UnnormalizedBatch(images=block_img[i]) for i in range(num_work)]

    with augment.pool(processes=-1, seed=1) as pool:
        for _ in range(num_iter):
            my_generator = create_generator(batches)
            batches_aug = pool.imap_batches(my_generator, output_buffer_size=5)
            for one_batch in batches_aug:
                for item in one_batch.images_aug:
                    try:
                        save_img(path, item)
                    except:
                        continue
                if len(os.listdir(path)) >= want_num:
                    return

                print('current num {}'.format(len(os.listdir(path))))

but it show me that:

Traceback (most recent call last):
  File "multible_aug_v2.py", line 111, in <module>
    main()
  File "multible_aug_v2.py", line 106, in main
    process_folder(folder_path)
  File "multible_aug_v2.py", line 91, in process_folder
    for one_batch in batches_aug:
  File "/data2/zhx3/env3/lib/python3.5/site-packages/imgaug/multicore.py", line 269, in imap_batches
    for batch in gen:
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<imgaug.augmentables.batches.UnnormalizedBatch object at 0x7fd7dbde7588>'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647",)'

**Comment by aleju** [comment]
What is your batch and how large is each image? A bit of googling indicates that this error can appear when a single batch exceeds 1GB of size in memory. It should be fixed by decreasing the batch size.

**Comment by Usernamezhx** [comment]
yeh. It can work. num of image is 1407. average 800k per image. I set the num batch to 8. It will show me multiprocessing.pool.MaybeEncodingError. but I change it to 16. It can work. thank you
