### ISSUE TITLE
AttributeError: module 'imgaug.augmenters' has no attribute 'MultiplyHueAndSaturation'

### ISSUE THREAD

**Issue by erwangccc** [aleju/imgaug#543]
Hi,guys,I meet this error when using imgaug. Meet this error when running `train.py`, I can use imgaug normally on other `.py` which is at same project. Is there a solution for this error?
I would appreciate it if you have suggestions.

    OS:ubantu16.04
    imgaug:0.3.0

`images = iaa.MultiplyHueAndSaturation(mul_hue=(0.8, 1.3), mul_saturation=(0.5, 1.5),per_channel=True)(image=images)`

```
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "utils/datasets.py", line 107, in __getitem__
    img_ia = color_enhance(img_ia)
  File "utils/augmentations.py", line 151, in color_enhance
    images = iaa.MultiplyHueAndSaturation(mul_hue=(0.8, 1.3), mul_saturation=(0.5, 1.5),per_channel=True)(image=images)
AttributeError: module 'imgaug.augmenters' has no attribute 'MultiplyHueAndSaturation''
```

**Comment by aleju** [comment]
Do you mean you can import `MultiplyHueAndSaturation` in other files, but not in your `train.py`? That would be weird. At least the augmenter should exist in 0.3.0. Do you maybe have a folder or file called `imgaug`?
You could run `print(dir(iaa))` to see what augmenters and functions are actually available. Also run `import imgaug; print(imgaug.__version__)` to make sure that you actually use 0.3.0 and not accidentally an older version.

**Comment by erwangccc** [comment]
Thank you for your help.
You got it right. 
I tried to print that information as you mentioned. When i print at other `.py`,there are 'MultiplyHueAndSaturation' and 'MultiplySaturation' and so on, the version is 0.3.0. But it is not when i print at `train.py`. the version is 0.2.9 even though I've never installed it before.

It is strange. Could i solve this problem via uninstalling the 0.2.9 version?

Thanks for your time.

**Comment by aleju** [comment]
Do you run all of these files with the exactly same command from the same directory? My best guess would be that they are executed in different python environments and that one of them has 0.2.9 installed and the other has 0.3.0 installed. Uninstalling 0.2.9 would then lead to an import error in one of the environments.
You can also try `import imgaug; print(imgaug.__file__)` to see from which path each of these files imports imgaug.

**Comment by erwangccc** [comment]
Hi, aleju. 

Thank you very much. you are right.
They are from different python environments.
I have setup the same environment.
Thank you
