### ISSUE TITLE
imgaug augmenters spoil the image

### ISSUE THREAD

**Issue by DmitryVlasovPrm** [aleju/imgaug#549]
Hello! I has faced such a problem. I try to rotate the image and get the spoiled image.
I can't understand what's the problem?
I used the following code:
```
from imgaug import augmenters as iaa
import matplotlib.pyplot as plt
import cv2

seq = iaa.Sequential([
    iaa.Affine(
        rotate=(-25, 25)
    )
])

image = cv2.imread("/Users/dmitry/Desktop/car.png")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_aug = seq(images=image)

plt.imshow(image_aug)
```
Input image:
![car](https://user-images.githubusercontent.com/57285246/71780472-c016f380-2fe4-11ea-892e-256e143f5a82.png)
Output image:
![output_car](https://user-images.githubusercontent.com/57285246/71780467-ad042380-2fe4-11ea-9065-a911aae4becd.png)

**Comment by aleju** [comment]
There's just a small typo in your code: `image_aug = seq(images=image)` should be `image_aug = seq(image=image)` or `image_aug = seq(images=[image])[0]` -- mind the singular/plural `image` vs `imageS`.
Without this adjustment the method will assume that you have `H` times `(W, 3)` grayscale images for a single input image with shape `(H, W, 3)` and rotate each of these `(W, 3)` images individually.

**Comment by DmitryVlasovPrm** [comment]
@aleju, thank you so much!
