### ISSUE TITLE
padding not working ?

### ISSUE THREAD

**Issue by FenryrMKIII** [aleju/imgaug#559]
MWE : 

```
import imgaug as ia
from imgaug import augmenters as iaa

image = ia.quokka(size=(256, 256))
ia.imshow(image) 

margin = 50
bbox = ia.BoundingBoxesOnImage([
    ia.BoundingBox(x1=0+margin, y1=0+margin, 
                x2=image.shape[1]-margin, y2=image.shape[0]-margin)], 
                shape=image.shape)
ia.imshow(bbox.draw_on_image(image)) 

seq = iaa.Sequential([iaa.Pad(px=100,pad_mode='constant', pad_cval=0, keep_size=False)])
imgAug, bboxAug = seq.augment(images = image, bounding_boxes=bbox)
ia.imshow(bboxAug.draw_on_image(imgAug))

```

returns the error : 

`ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (369,203)`

so somehow when using padding the third dimensions (channels) get modified from 3 (RGB) to 203.  What is the issue here ? I don't know the package well enough yet to find the issue. 

I will keep looking but if someone has the solution in the meantime I am all hear

**Comment by aleju** [comment]
Looks like a common typo:
Change
```python
seq.augment(images = image, bounding_boxes=bbox)
```
to
```python
seq.augment(image = image, bounding_boxes=bbox)
```
Then it seems to work for me.

**Comment by FenryrMKIII** [comment]
Thanks I will try this!
If that's the solution, I am a *** idiot and I am sorry

**Comment by aleju** [comment]
No worries, mixing up singular/plural at that point seems to be the most common error that people make when using the library.
