### ISSUE TITLE
Pickle Errors with Convolve Augmenters

### ISSUE THREAD

**Issue by abnera** [aleju/imgaug#58]
Four augmenters that use the Convolve class: (Sharpen, Emboss,  EdgeDetect and DirectEdgeDetect) are giving me pickle errors.

`AttributeError: Can't pickle local object 'Emboss.<locals>.create_matrices'`
Any easy way to fix this or make them pickle safe?

Regards @aleju

**Comment by aleju** [comment]
Are you using background augmentation? That will probably not work with these augmenters due to function pickling. Forgot about that use case. The quick fix for now would be to use non-background/normal augmentation until the core problem is fixed.

**Comment by abnera** [comment]
@aleju Just to confirm. You say that for now, I should use them as a preprocessing step, save the images and then load them? Is that what you refer to mainly background augmentation?

I saw in your cat detection example you do use it in the background with pytorch by creating a BackgroundAugmenter. I wonder if I could do a hacky/patch to work around that. I basically have a keras generator function and call `seq.augment_images(img)` in every image.

**Comment by aleju** [comment]
I think the cat detection code didn't use Sharpen/Emboss/EdgeDetect/DirectedEdgeDetect. These all use a pickled function, so they can't easily be used with multiprocessing (i.e. spawning background processes). The library has stuff for background augmentation, which rely on multiprocessing. Basically if you use `BackgroundAugmenter` or `.augment_batches(..., background=True)` then you use the library's background functionality. I suspect that this is also the case when using keras with generator functions. I vaguely recall that they use `multiprocessing.pool` to load batches from the generator, which would then cause the same pickle error. Maybe that can be deactivated in keras? Otherwise you have to write a loop, so that you avoid using a generator for keras.

**Comment by abnera** [comment]
Actually, your comments help me solved it.

Before Keras had a parameter named pickled_safe on fit. Now it's refractor to use_multiprocessing.
So `use_multiprocessing=False` uses multi-thread which is pickle-safe. I just tested and they all are working.

I'm using the example augmentations from the link below cat pytorch.
https://github.com/aleju/cat-bbs/blob/84952b2a3caec8488df92174ddaf30de45538d11/train.py#L74

Thanks!!!

**Comment by bryanworthen** [comment]
Hi, I am using imgaug (and it's awesome!) v. 0.2.5, as retrieved from 'pip install imgaug', and am running into this error message.

_pickle.PicklingError: Can't pickle <function Emboss.<locals>.create_matrices at 0x7f8f52099048>: attribute lookup create_matrices on imgaug.augmenters.convolutional failed.

I can't quite tell from the comments above, but it sounded like there was was a fix that would require some time? Is that still the case?

Note that the single-process version works fine, we're just trying to speed things up.

Thanks!!!

**Comment by jewfro-cuban** [comment]
I think I've managed to work with Convolution based augmenters and multiprocessing (at least in pytorch).
I'm getting the closure create_matrices out to a wrapper class, create an instance of that class instead and pass the method. This required a minor modification to convolutional.py

For example for MotionBlur:

 import imgaug as ia
 from imgaug.augmenters import convolutional as iaa_convolutional
 from imgaug import augmenters as iaa


 class CreateMatricesWrapper:
     '''

     '''
     def __init__(self, k_param, angle_param, direction_param, order):
         self.k_param = k_param
         self.angle_param = angle_param
         self.direction_param = direction_param
         self.order = order

     def create_matrices(self, image, nb_channels, random_state_func):
         # avoid cyclic import between blur and geometric
         from imgaug.augmenters import geometric as iaa_geometric

         # force discrete for k_sample via int() in case of stochastic parameter
         k_sample = int(self.k_param.draw_sample(random_state=random_state_func))
         angle_sample = self.angle_param.draw_sample(random_state=random_state_func)
         direction_sample = self.direction_param.draw_sample(random_state=random_state_func)

         k_sample = k_sample if k_sample % 2 != 0 else k_sample + 1
         direction_sample = np.clip(direction_sample, -1.0, 1.0)
         direction_sample = (direction_sample + 1.0) / 2.0

         matrix = np.zeros((k_sample, k_sample), dtype=np.float32)
         matrix[:, k_sample // 2] = np.linspace(float(direction_sample), 1.0 - float(direction_sample), num=k_sample)
         rot = iaa_geometric.Affine(rotate=angle_sample, order=self.order)
         matrix = (rot.augment_image((matrix * 255).astype(np.uint8)) / 255.0).astype(np.float32)

         return [matrix / np.sum(matrix)] * nb_channels

def MotionBlur(k=5, angle=(0, 360), direction=(-1.0, 1.0), order=1, name=None, deterministic=False, random_state=None):
    """
    Blur images in a way that fakes camera or object movements.
    dtype support::
        See ``imgaug.augmenters.convolutional.Convolve``.
    Parameters
    ----------
    k : int or tuple of int or list of int or imgaug.parameters.StochasticParameter, optional
        Kernel size to use.
            * If a single int, then that value will be used for the height
              and width of the kernel.
            * If a tuple of two ints ``(a, b)``, then the kernel size will be
              sampled from the interval ``[a..b]``.
            * If a list, then a random value will be sampled from that list per image.
            * If a StochasticParameter, then ``N`` samples will be drawn from
              that parameter per ``N`` input images, each representing the kernel
              size for the nth image.
    angle : number or tuple of number or list of number or imgaug.parameters.StochasticParameter, optional
        Angle of the motion blur in degrees (clockwise, relative to top center direction).
            * If a number, exactly that value will be used.
            * If a tuple ``(a, b)``, a random value from the range ``a <= x <= b`` will
              be sampled per image.
            * If a list, then a random value will be sampled from that list per image.
            * If a StochasticParameter, a value will be sampled from the
              parameter per image.
    direction : number or tuple of number or list of number or imgaug.parameters.StochasticParameter, optional
        Forward/backward direction of the motion blur. Lower values towards -1.0 will point the motion blur towards
        the back (with angle provided via `angle`). Higher values towards 1.0 will point the motion blur forward.
        A value of 0.0 leads to a uniformly (but still angled) motion blur.
            * If a number, exactly that value will be used.
            * If a tuple ``(a, b)``, a random value from the range ``a <= x <= b`` will
              be sampled per image.
            * If a list, then a random value will be sampled from that list per image.
            * If a StochasticParameter, a value will be sampled from the
              parameter per image.
    order : int or iterable of int or imgaug.ALL or imgaug.parameters.StochasticParameter, optional
        Interpolation order to use when rotating the kernel according to `angle`.
        See :func:`imgaug.augmenters.geometric.Affine.__init__`.
        Recommended to be ``0`` or ``1``, with ``0`` being faster, but less continuous/smooth as `angle` is changed,
         particularly around multiple of 45 degrees.
     name : None or str, optional
         See :func:`imgaug.augmenters.meta.Augmenter.__init__`.
     deterministic : bool, optional
         See :func:`imgaug.augmenters.meta.Augmenter.__init__`.
     random_state : None or int or imgaug.random.RNG or numpy.random.Generator or
         numpy.random.bit_generator.BitGenerator or numpy.random.SeedSequence or numpy.random.RandomState, optional
         See :func:`imgaug.augmenters.meta.Augmenter.__init__`.
     Examples
     --------
     >>> aug = iaa.MotionBlur(k=15)
     Apply motion blur with a kernel size of ``15x15`` pixels to images.
     >>> aug = iaa.MotionBlur(k=15, angle=[-45, 45])
     Apply motion blur with a kernel size of ``15x15`` pixels and a blur angle
     of either ``-45`` or ``45`` degrees (randomly picked per image).
     """
     # TODO allow (1, None) and set to identity matrix if k == 1
     k_param = iap.handle_discrete_param(k, "k", value_range=(3, None), tuple_to_uniform=True, list_to_choice=True,
                                         allow_floats=False)
     angle_param = iap.handle_continuous_param(angle, "angle", value_range=None, tuple_to_uniform=True,
                                               list_to_choice=True)
     direction_param = iap.handle_continuous_param(direction, "direction", value_range=(-1.0 - 1e-6, 1.0 + 1e-6),
                                                   tuple_to_uniform=True, list_to_choice=True)

     if name is None:
         name = "Unnamed%s" % (ia.caller_name(),)

     cmw = CreateMatricesWrapper(k_param, angle_param, direction_param, order)

     return iaa_convolutional.Convolve(cmw.create_matrices, name=name, deterministic=deterministic,
                                       random_state=random_state)
