### ISSUE TITLE
Undefined `load_batches` in Example

### ISSUE THREAD

**Issue by go2carter** [aleju/imgaug#59]
In the example found [here](https://github.com/aleju/imgaug/blob/master/docs/source/examples_basics.rst), the first example references some `load_batches` command that's not defined earlier. Searching in the `augmenters.py` file (imported as `iaa`) also did not yield any results).

What is that method?

**Comment by aleju** [comment]
That's just a generic placeholder for a function that loads batches, i.e. usually images and labels, though here only images for simplicity. The function is expected to exist in most machine learning experiments, but you will have to define it. You can load images using [scipy.ndimage.imread](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html).

**Comment by go2carter** [comment]
Understood, danke :)

**Comment by chloe2019** [comment]
> That's just a generic placeholder for a function that loads batches, i.e. usually images and labels, though here only images for simplicity. The function is expected to exist in most machine learning experiments, but you will have to define it. You can load images using [scipy.ndimage.imread](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html).
can you share this load_batch function ???
