### ISSUE TITLE
ZCA whitening and Related Questions.

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#6]
it's more of a question rather than an issue.
Have you considered implementing ZCA whitening?
I have a simple implementation. But It doesn't seem to work on color images.

For example, on [CIFAR10](http://www.cs.utoronto.ca/~kriz/cifar.html) dataset, the result of ZCA whitening is distorted images where only few color pixels remain and rest of the image gets all distorted.

Also, ZCA whitening acts as a low pass filter according to some sources. What are other techniques that act as a low pass filter? Gaussian Blurring???

**Comment by aleju** [comment]
Haven't really thought about it yet. It is in the keras augmenter, but aside from that I've never seen it referenced in any paper and can't really find many example images regarding its effects. I guess the best way would be to just implement it and look at its effects and performance and then keep it if both factors seem good enough.
And yes, gaussian blurring should be a low pass filter as it removes high frequency components.

**Comment by SarthakYadav** [comment]
here's a stack exchange page that shows (and explains a bit) the effects of ZCA whitening

[Difference between ZCA whitening and PCA whitening](http://stats.stackexchange.com/questions/117427/what-is-the-difference-between-zca-whitening-and-pca-whitening)
