### ISSUE TITLE
Checking image shape

### ISSUE THREAD

**Issue by arahusky** [aleju/imgaug#61]
https://github.com/aleju/imgaug/blob/32e8aa7935e187492fc98951bce493244211fbdd/imgaug/imgaug.py#L204

is this line correct? should not we rather check for ```len(image.shape) == 2```?

if this is implemented, this code will break line https://github.com/aleju/imgaug/blob/master/imgaug/augmenters/geometric.py#L940
which should be probably updated to ```result[i] = np.reshape(warped, (result[i].shape)) ```

**Comment by nektor211** [comment]
About the second point, it appears that cv2.warpPerspictive does not preserve the third dimension for single channel images. An example code that doesn't work on current master and works after applying the fix:

```
from imgaug import augmenters as iaa
from imgaug import parameters as iap
import numpy as np

images = np.random.randint(0, 255, (16, 128, 128), dtype=np.uint8)
seq = iaa.Sequential([
    iaa.PerspectiveTransform(scale=iap.Choice([0.0, 0.025, 0.05, 0.075, 0.10]), name='perspective'),
])
seq_det = seq.to_deterministic()
for i in range(16):
    images_aug = seq_det.augment_image(images[i])
    plt.imshow(images_aug)
    plt.show()
```
