### ISSUE TITLE
normalize_shape causes ambiguities 

### ISSUE THREAD

**Issue by Erotemic** [aleju/imgaug#616]
I just spent a good hour tracking down this bug. 

It turns out that when you pass the `shape` keyword argument to `KeypointsOnImage`  or `BoundingBoxesOnImage` they use `normalize_shape` to preprocess the input. If `shape` is a tuple then there is no problem. 

However, the issue happens when I pass `shape` as a numpy array. Instead of trusting that what I gave it represents the shape of the image, I guess it assumes I'm passing the image itself and returns the `arr.shape` attribute, which turns out to be (2,) when the ndarray is actually representing the shape (which happens often when you want to mathematically manipulate shapes). 

I'm going to guess that this was probably put in there as a convenience, but I found the behavior unintuitive. I'm guessing others might as well. It might be a good idea to discourage the passing of ndarrays as the shape parameter. Because this feature has already been released, I don't think it would be a good idea to backtrack on it, but it may be a good idea to raise a warning whenever the user passes a ndarray into normalize_shape saying that they should be passing the shape tuple instead. 

If the maintainers of the repo really like the current behavior of normalize shape and want to keep it that way, I would understand. It is somewhat convenient if you are in the know, but my intuition is that this might trip up a lot of other users and it might be a good idea to simplify the API and disallow or discourage passing the actual image as the shape parameter.

**Comment by aleju** [comment]
This is now changed in master: In `BoundingBoxOnImages` and similar `*OnImages` instances it is now deprecated to provide the `shape` as a numpy array. In other methods that allow for both numpy arrays and shape inputs (e.g. `BoundingBox.clip_out_of_image(image)`), the `image` input must now have more than one dimension.

Thanks for pointing this out. Hadn't expected anyone to do shape computations via numpy arrays.
And yes, it was added for convenience and to decrease the likelihood that people forget to provide the channel axis when the underlying image actually does have channels.
