### ISSUE TITLE
Augment bounding boxes is broken when only _augment_keypoints is defined

### ISSUE THREAD

**Issue by Erotemic** [aleju/imgaug#617]
I have an augmenter that implements `_augment_keypoints` and `_augment_images`, which should be sufficient for augmenting both vector and raster representations of data. However, I noticed when I updated imgaug, my boxes were no longer being augmented. 

It looks like 0.4.0 broke the behavior where `augment_bounding_boxes` used to work as long as `_augment_keypoints` was defined. 

The currently implementation in Augmenter is:

```python
    def _augment_bounding_boxes(self, bounding_boxes_on_images, random_state,
                                parents, hooks):
        return bounding_boxes_on_images

    def _augment_polygons(self, polygons_on_images, random_state, parents,
                          hooks):
        return polygons_on_images
```

However, if only the two aforementioned functions are implemented then the augmenter will change the image, but the boxes will be unchanged. At the very least this should cause an Exception, but I think a better fix would simply be to use the _augment_keypoints function if it exists: 

```python
    def _augment_bounding_boxes(self, bounding_boxes_on_images, random_state,
                                parents, hooks):
        return self._augment_bounding_boxes_as_keypoints(
            bounding_boxes_on_images, random_state, parents, hooks)

    def _augment_polygons(self, polygons_on_images, random_state, parents,
                          hooks):

        return self._augment_polygons_boxes_as_keypoints(
            polygons_on_images, random_state, parents, hooks)
```

**Comment by aleju** [comment]
This issue is now fixed in master. Thanks for reporting it.
