### ISSUE TITLE
Python2 compatibility broken : Imageio

### ISSUE THREAD

**Issue by MSutt** [aleju/imgaug#627]
The new imageio version does not support python2 anymore.
running `pip install imgaug` with python2 leads to this error :
```Collecting imageio
  Using cached imageio-2.8.0.tar.gz (3.3 MB)
ERROR: Package 'imageio' requires a different Python: 2.7.16 not in '>=3.5't```

**Comment by aleju** [comment]
The requirements should now be fixed in master so that the imagio version is restricted to an older one for python <3.5.
Thanks for reporting this.
