### ISSUE TITLE
Keep information during rotate 

### ISSUE THREAD

**Issue by sizhky** [aleju/imgaug#629]
Hi,

Is it possible to return a rotated image without losing the information? E.g.

Sometimes if the rotation is too aggressive there is missing content - 
![image](https://user-images.githubusercontent.com/3656100/75513912-36036e00-5a1c-11ea-82f5-27c9f16e064e.png)

Instead what I am asking is a way to return image with a modified aspect ratio such that original image is intact.
![image](https://user-images.githubusercontent.com/3656100/75513886-1ff5ad80-5a1c-11ea-95d4-a67ab0a7cddb.png)

**Comment by aleju** [comment]
Do you mean `Affine` rotations? In that case, try calling it as in `Affine(rotate=..., fit_output=True)`. It should do what you want.

**Comment by sizhky** [comment]
Thank you! :smile_cat:
