### ISSUE TITLE
PiecewiseAffine returns (-1, -1) for augmented keypoints that would be outside the image

### ISSUE THREAD

**Issue by NKlug** [aleju/imgaug#63]
PiecewiseAffine returns (-1, -1), when the augmented keypoint would be outside of the image.

Corresponding Code:
https://github.com/aleju/imgaug/blob/c1aa569d15cd98ca77bd12af895ae088ec826c90/imgaug/augmenters/geometric.py#L796-L797

As I found out, the -1 is assigned in inverse() in skimage/transform/_geometric.py

Is this intended? All the other augmentation techniques I've used so far just return the coordinates, even if they are bigger or smaller than the image dimensions.

**Comment by aleju** [comment]
Thanks for pointing this not. That was not intended. I reworked how PiecewiseAffine works and keypoints should now no longer be moved out of the image (in most cases -- seems to still happen, but only rarely when using very strong distortions). Keypoints that were already outside of the image before running PiecewiseAffine remain now at the same coordinates.

**Comment by oak-tree** [comment]
I had the same issue, @aleju  maybe it should do `boundaries check` for `keypoints`   after running the `transformation`?

**Comment by aleju** [comment]
I just pushed a version which fixes another bug in PiecewiseAffine's keypoint augmentation. The newest version in the repo should now no longer move keypoints out of the image plane (unless very high scale values are used).

**Comment by oak-tree** [comment]
Thanks!, I'll give it a try

**Comment by oak-tree** [comment]
Just tried it. After several different runs I got 

> OverflowError: Python int too large to convert to C long



Stacktrace

>   File "/home/oak/venv2/local/lib/python2.7/site-packages/imgaug/augmenters/meta.py", line 503, in augment_keypoints
>     hooks=hooks
>   File "/home/oak/venv2/local/lib/python2.7/site-packages/imgaug/augmenters/meta.py", line 1360, in _augment_keypoints
>     hooks=hooks
>   File "/home/oak/venv2/local/lib/python2.7/site-packages/imgaug/augmenters/meta.py", line 503, in augment_keypoints
>     hooks=hooks
>   File "/home/oak/venv2/local/lib/python2.7/site-packages/imgaug/augmenters/geometric.py", line 522, in _augment_keypoints
>     coords = keypoints_on_image.get_coords_array()
>   File "/home/oak/venv2/local/lib/python2.7/site-packages/imgaug/imgaug.py", line 1021, in get_coords_array
>     result[i, 1] = keypoint.y
>

**Comment by aleju** [comment]
That line is before PiecewiseAffine warps the keypoints. So the input keypoints seem to already be wrong. Either the output of a different augmenter is wrong or your initial keypoint coordinates/shapes (before any augmentation) are wrong. Do you use any other augmenters that change keypoint positions?

**Comment by oak-tree** [comment]
See my update above: the issue was that I did f(f(f(f(f(f(f.....f(x))))))) where `f` the augmenation function. I do now f(x),f(x),....,f(x). and it works well

**Comment by aleju** [comment]
Did your `f` only contain PiecewiseAffine? Because that augmenter shouldn't even change keypoints any more once they are outside the bounds of the image (with height/width specified in `KeypointsOnImage.shape`), but the error message looks like they overflow for some reason.

**Comment by oak-tree** [comment]
## Definition f
```
 self.transormator = iaa.Sequential([
                iaa.Crop(px=(crop_min, crop_max)),  # crop images from each side by 0 to 16px (randomly chosen)
                iaa.Fliplr(horizontal_flip),  # horizontally flip 50% of the images
                iaa.Flipud(vetical_flip),
                iaa.GaussianBlur(sigma=sigma),  # blur images with a sigma of 0 to 3.0
                iaa.Affine(rotate=rotate, shear=shear),
            ])
```
# Use of f
```
def random_transform(x,x_keypoints):
                self.transormator.to_deterministic()
                augmented_x = self.transormator.augment_images([x])
                augmented_x = np.asarray(augmented_x, dtype=floatx())
                augmented_boxes = self.transormator.augment_keypoints([x_keypoints])
```

Calling random_transform many times changes `x_keypoints` to be outside of the image bounds and eventually result with an overflow
