### ISSUE TITLE
Multiple segmentation maps on one image

### ISSUE THREAD

**Issue by Mabinogiysk** [aleju/imgaug#633]
I need bounding box and segmentation at the same time. If two adjacent objects on one image belong to the same category, I cannot separate them from each other after augmentation using `SegmentationMapsOnImage`. What I need is one segmentation map for one object and multiple segmentaion maps on one image.
Is there any solutions?

**Comment by aleju** [comment]
`SegmentationMapsOnImage` accepts arrays of shape `(H, W, C)`, which kind of allows you to provide multiple segmentation map arrays via multiple channels. Is that what you want?

**Comment by Mabinogiysk** [comment]
> `SegmentationMapsOnImage` accepts arrays of shape `(H, W, C)`, which kind of allows you to provide multiple segmentation map arrays via multiple channels. Is that what you want?

Thank you very much.
