### ISSUE TITLE
import problem with imgaug and tensorflow at the same time

### ISSUE THREAD

**Issue by galitus** [aleju/imgaug#636]
Alright, I'm using gentoo linux, so everything is compiled from source.
I have problem to import imgaug and tensorflow at the same time.

python: 3.6.9
gcc 9.2.0
protobuf 3.8.0
tensorflow 1.14.0
matplotlib 2.2.2
scikits_image 0.14.2
imageio 2.6.1
scipy 1.1.0
numpy 1.15.4

Problem:
`Python 3.6.9 (default, Nov 14 2019, 17:07:05) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imgaug
>>> import tensorflow
[libprotobuf ERROR /var/tmp/portage/dev-libs/protobuf-3.8.0/work/protobuf-3.8.0/src/google/protobuf/descriptor_database.cc:172] Symbol name "tensorflow.TensorShapeProto" conflicts with the existing symbol "tensorflow.TensorShapeProto".
[libprotobuf FATAL /var/tmp/portage/dev-libs/protobuf-3.8.0/work/protobuf-3.8.0/src/google/protobuf/descriptor.cc:1367] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted`

So python is aborting in the end.

Any idea why? 
I recompiled tensorflow, reinstalled imgaug and everything but it didn't help.
Please push me in the right direction.

Greetings

**Comment by aleju** [comment]
Have you tried inverting the import order, i.e. first tensorflow and afterwards imgaug? There was another issue where turning the order around fixed an error, though I think it was the other way round. If that doesn't fix it, then I'm not really sure what the cause is.

**Comment by galitus** [comment]
Hey, 

I already tried this. Same problem.

It seems to be a opencv problem?
imgaug is using opencv which is using protobuf and tensorflow depends on protobuf also

I only found this comment:
https://github.com/opencv/opencv/issues/10949#issuecomment-369291969

I don't know if this helps to track down the problem.

Greetings

**Comment by galitus** [comment]
okay, I found the solution opencv 3.4.x was the reason, with 4.1.x it is working

so I close the issue : )
thanks for the help
