### ISSUE TITLE
Augment overlapping segmentation masks

### ISSUE THREAD

**Issue by pluniak** [aleju/imgaug#637]
Hello,

I have N segmentation maps per image that I need to augment together with the image. I'm doing this with this awesome repo using `ia.augmentables.segmaps.SegmentationMapsOnImage()` and passing in the resulting image and mask objects to `iaa.Sequential()` . That's working fine, but from my understanding it doesn't allow for overlapping masks as `ia.augmentables.segmaps.SegmentationMapsOnImage()` takes an integer mask with N values instead of a cube of boolean masks with N channels. That is a problem e.g. if you want to segment complete humans and human eyes at the same time, because the according segmentation masks are overlapping.
Is there any solution/workaround for this like passing in a list of boolean masks to `iaa.Sequential()` instead of the single integer mask? I've been looking for a possibility for a while but haven't found one yet, so any help is greatly appreciated.

Best,
Philipp

**Comment by aleju** [comment]
`SegmentationMapsOnImage` does accept `(H,W,C)` integer arrays, where each channel represents an independent segmentation map. The intended use is e.g. for instance segmentation, where each class gets its own channel. That seems like it should cover the case of segmenting both humans and human eyes in the same image, doesn't it?

**Comment by pluniak** [comment]
@aleju Thanks for the info. That's very good to know. Is it possible that the behavior I described above applied to `SegmentationMapOnImage` and was changed in `SegmentationMapsOnImage`? I updated the repo and the original documentation of `SegmentationMapOnImage` is not available anymore.

**Comment by davodogster** [comment]
@pluniak Hi Phillip were you able to augment overlapping instances? I need to crop augmentation them, and also the bounding boxes at the same time. Do you know how to do this?
