### ISSUE TITLE
Rotation by 90 degrees results in a black border

### ISSUE THREAD

**Issue by BAILOOL** [aleju/imgaug#64]
Running ``` iaa.Affine(rotate=90)``` results in a black border for a square image.

![image](https://user-images.githubusercontent.com/11172777/30736875-759edfa0-9fbf-11e7-9e18-3fae47fe1fa2.png)

**Comment by aleju** [comment]
Thanks for the info. There was a slightly wrong shift value in `Affine`. This should now be fixed.
If you still encounter black borders and don't want them, you can probably get rid of them via something like `Affine(rotate=85, mode="edge")`, which just repeats the closes edge pixels.
