### ISSUE TITLE
Squared does not seem to change the shape of the cutouts

### ISSUE THREAD

**Issue by Aaronzinhoo** [aleju/imgaug#653]
I am on a conda evironment using imgaug v0.4.0 on Windows 10.

When using the code below and applying it to an image the cutouts do not change shape and are consistently square. I am sure this is not intended behaviour and have tried this with squared set to False as well with no change. 

(Note: I am running other augmentations as well but this is the only one that does not produce intended results.)
```
aug = iaa.Cutout(nb_iterations=(1, 3), size=0.25, squared=0.5,
                   fill_mode="constant", cval=(0, 255),
                   fill_per_channel=0.5)
```

Any help or info would be great! Thanks

**Comment by aleju** [comment]
You just forgot to change `size` to a non-constant value, e.g. `size=(0.05, 0.5)`. Otherwise every cutout region will have 25% size of the x- and y-axis. (I guess your images are square, leading to the cutout regions always being squared?)

**Comment by Aaronzinhoo** [comment]
Ahh that makes sense! thanks so much, yes you are right.
