### ISSUE TITLE
Different cval per channel

### ISSUE THREAD

**Issue by cdjameson** [aleju/imgaug#667]
I'm needing to have different `cval` arguments for each channel of the image, specifically for the Affine augmentation class.

Specifics:
I have a two channel image where the first channel has a "white" background the the second channel has a "black" background, so when I'm performing Affine transformations I need `cval = 255` for the first channel and `cval = 0` for the second, but this doesn't seem to be supported in the API docs. I'm thinking something along the lines of
```
aug = iaa.Affine(scale=(0.7,1.2),cval=[(255,255),(0,0)])
```
I would like to augment the channels together so that I can continue doing random translations/scales/etc instead of having to augment them with separate augmenter objects which would require doing deterministic augmentations.

**Comment by aleju** [comment]
If all of your images always have exactly two channels, then `import imgaug.parameters as iap; iaa.Affine(..., cval=iap.DeterministicList([255, 0]))` should currently do the job.

**Comment by cdjameson** [comment]
This does work for individual deterministic values, so I can close the issue if you'd prefer since that's what I asked about, but is there any way to do this with a range of values? I tried wrapping `DeterministicList` around other `parameters` to no avail:
```
iaa.Affine(..., cval=iap.DeterministicList([iap.Uniform(250,255),iap.Uniform(0,7)]))
```
raises a `TypeError` due to not providing simple `float`s to `DeterministicList`

**Comment by aleju** [comment]
Nevermind, I just saw that it wouldn't have worked anyways as Affine is quite dumb and always tries to sample (N, 3) arrays for cval, assuming that the input image is RGB.

You can however solve this task by just implementing a custom parameter. The following should work in principle (didn't test it yet):
```python
import numpy as np
import imgaug.parameters as iap


class TwoChannels(iap.StochasticParameter):
    def __init__(self, channel1, channel2):
        super(TwoChannels, self).__init__()

        self.channel1 = channel1
        self.channel2 = channel2

    def _draw_samples(self, size, random_state):
        # Affine requests (N, 3) here, but we can ignore the second axis.
        # The output is not verified anywhere as far as I can see.
        nb_images = size.shape[0]
        channel1 = self.channel1.draw_samples((nb_images, 1), random_state=random_state)
        channel2 = self.channel2.draw_samples((nb_images, 1), random_state=random_state)
        return np.concatenate([channel1, channel2], axis=1)
```
then just provide it as `cval=TwoChannels(iap.Uniform(250, 255), iap.Uniform(0, 7))`.

**Comment by cdjameson** [comment]
This works brilliantly; I should have thought to subclass StochasticParameter! For posterity's sake, I confirmed that the first method works on 3-channel images, and the second method works for both 2- and 3-channel images with the typo `size.shape[0]` changed to `size[0]`.

Thanks!
