### ISSUE TITLE
cval not behaving correctly when given float value

### ISSUE THREAD

**Issue by cdjameson** [aleju/imgaug#669]
According to [the docs](https://imgaug.readthedocs.io/en/latest/source/api_augmenters_geometric.html) `cval` should accept float values and create new pixels according to the given value:
> **cval** (number ... ) – The constant value to use when filling in newly created pixels. ... _It may be a float value._

However in practice (with imgaug.augmenters.Affine at least) this does not work. It appears that the actual value being returned is `int(cval)`. My particular use case is with `float32` images ranging from `[0.0, 1.0]`.

The issue can be reproduced this way:
```
import numpy as np
import matplotlib.pyplot as plt
import imgaug as ia
import imgaug.augmenters as iaa

im = np.array(ia.quokka(size=(256,256)),dtype=np.float32)
im = im/(2**8-1)
print("First pixel = " + str(im[0,0,:]))

aug = iaa.Affine(scale=0.8,cval=0.4)
aug_im = aug(image=im)
print("First pixel = " + str(aug_im[0,0,:]))

plt.imsave('./regular.png',im)
plt.imsave('./scaled.png',aug_im)
```

Output:
```
First pixel = [0.19215687 0.30588236 0.32156864]
First pixel = [0. 0. 0.]
```
Where this should now be `[0.4 0.4 0.4]`.

Resulting images:
![regular](https://user-images.githubusercontent.com/65251787/82463686-1e6fda80-9a8b-11ea-9548-f18daa8fadf3.png)
![scaled](https://user-images.githubusercontent.com/65251787/82463697-20399e00-9a8b-11ea-8e3d-869dd97ec31c.png)

If this can't be fixed please update the documentation, as currently this is not the expected behavior.

**Comment by aleju** [comment]
This should now be fixed in master. Thanks for reporting the issue!
