### ISSUE TITLE
Shifted augumented segmentation mask

### ISSUE THREAD

**Issue by Adblu** [aleju/imgaug#675]
I am getting shifted segmentation mask. It keeps proportions, which is good but is shifted....
Why such weird behavior ?

**Comment by aleju** [comment]
Which operations are you using? Do you have example code how you call them with your data? Usually, segmentation masks and images should match.

**Comment by Adblu** [comment]
My fault, I had bug in the code. Im using segmentation mask and works 100%. Sorry for trouble.
