### ISSUE TITLE
OneOf wrong behaviour

### ISSUE THREAD

**Issue by vimalaguti** [aleju/imgaug#68]
Hi,
looks like there is something broken there, I suppose.

With this code, I get at the same time: dropout and Add+
Dropout is always used.
Never get Add- nor constrastNorm.
```
color = iaa.Sometimes(1,iaa.OneOf([
        iaa.Add((-50, -20)),
        iaa.Add((20, 50)),
        iaa.ContrastNormalization((0.3, 0.5)),
        iaa.ContrastNormalization((1.5, 1.9))
        iaa.CoarseDropout(p=0.05, size_percent=0.2)
        ]))
```

I use like this (I know, it's not good..):
```
img1 = iaa.Sequential([iaa.Fliplr(p=1),color]).augment_image(img)
img2 = iaa.Sequential([iaa.Fliplr(p=1),color]).augment_image(img)
```

**Comment by vimalaguti** [comment]
Looks like there is something wrong when I use iaa.Sometimes(iaa.OneOf())
When I use OneOf alone, it works fine.

**Comment by aleju** [comment]
Should be fixed now. `Sometimes` falsely turned `OneOf` into a `Sequential`.
