### ISSUE TITLE
MixUp || CutMix Augmentation! Implementation Possible?

### ISSUE THREAD

**Issue by innat** [aleju/imgaug#686]
I'm trying to implement mixup and `cutmix `augmentation in `matterport/maskrcnn` network which is mainly allows augmentation of this library. I've tried out some cool library with it, however, jut to know is it possible to implement `cutmix` or `mixup `augmentation as well?

**Comment by SunAriesCN** [comment]
Hi, have you ever find other ways to implement cutmix or mixup with imaug? @innat
