### ISSUE TITLE
Can't pass array of masks to seq

### ISSUE THREAD

**Issue by MikitaBelikau** [aleju/imgaug#697]
I want to pass image and array of corresponding binary masks to seq. Each mask file has only 1 mask.

Code

`
    img = imread(imagePath)

    img = resize(img, (IMAGE_HEIGHT, IMAGE_WIDTH), mode='constant', preserve_range=True)
    img = np.expand_dims(img, axis=-1)
    img = np.expand_dims(img, axis=0)

    masksFolderPath = os.path.join(path, 'masks')
    masksCount = len(os.listdir(masksFolderPath)) 

    mask = np.zeros((masksCount, IMAGE_HEIGHT, IMAGE_WIDTH, 1), dtype=np.int)

    i = 0
    for mask_file in next(os.walk(masksFolderPath))[2]:
        maskPath = os.path.join(masksFolderPath, mask_file)
        mask_ = imread(maskPath)

        ...................................

        mask_ = np.expand_dims(mask_, axis=-1)

        #mask = np.maximum(mask, mask_) # accumulate all masks in one image
        mask[i, :, :] = mask_
        i += 1

    #mask = np.expand_dims(mask, axis=0)
    mask = np.array(mask, dtype=np.int)

    i = 0
    for i in range(AUGMANTED_IMAGES_NUMBER):
        augmented_image, augmented_mask = seq(images=img, segmentation_maps=mask)
` 

at the last line I got 

"Tried to convert data of form 'array[int]' to 'List[SegmentationMapsOnImage]'. This required exactly 2 corresponding image shapes, but instead 1 were provided. This can happen e.g. if more images were provided than corresponding augmentables, e.g. 10 images but only 5 segmentation maps. It can also happen if there was a misunderstanding about how an augmentable input would be parsed. E.g. if a list of N (x,y)-tuples was provided as keypoints and the expectation was that this would be parsed as one keypoint per image for N images, but instead it was parsed as N keypoints on 1 image (i.e. 'shapes' would have to contain 1 shape, but N would be provided). To avoid this, it is recommended to provide imgaug standard classes, e.g. KeypointsOnImage for keypoints instead of lists of tuples."

I can not understand why this is happening, cause I am passing mask in a correct shape. 
Can you, please, help me?

**Comment by MikitaBelikau** [comment]
Ok, if no one knows, then another question: does imgaug require that in case of multiple masks for each image they (masks) need to be 'merged' to a one image where all masks will be placed? Because that's exactly what I want to avoid. I want to augment each individual mask - not merged one.

**Comment by aleju** [comment]
Hey, sorry for the late reply. I'm very busy currently with other things.

Following your mail I assume that what you want to achieve is to augment exactly 1 image and N masks on that image. If all of these masks have the same height and width you can merge them to a single array of shape `(1, H, W, N)`. Each channel (i.e. the fourth axis, `N`) would then contain one of these mask's content. The augmentation would happen according to `seq(image=<image array>, segmentation_maps=<(1, H, W, N) array>)`. Make sure here that you use `image=...`, not `imageS=...` as you only have a single image.

If your masks have different heights and widths it gets a little bit more complicated. Then you have to use something like the following:
```python
image = <image array>
masks_oi = [ia.SegmentationMasksOnImage(mask, shape=image.shape) for mask in masks]
seq_det = seq.to_deterministic()
image_aug = seq_det(image=image)
masks_aug = [seq_det(segmentation_masks=mask_oi).get_arr() for mask_oi in in masks_oi]
```
Essentially you "freeze" the random number generator via `to_deterministic()` so that it auto-resets itself after each augmentation call. This way you can make multiple calls and get every time the same augmentations, just applied to different inputs. Make sure to call `to_deterministic()` once per batch, otherwise you would always get the same augmentations for every batch.

**Comment by MikitaBelikau** [comment]
Thanks for your help!

It solved the issue.

Here's the snippet

`masksCount = len(os.listdir(masksFolderPath)) 

    mask = np.zeros((1, IMAGE_HEIGHT, IMAGE_WIDTH, masksCount), dtype=np.int)

    i = 0
    for mask_file in next(os.walk(masksFolderPath))[2]:
        maskPath = os.path.join(masksFolderPath, mask_file)
        mask_ = imread(maskPath)

        mask_ = np.expand_dims(mask_, axis=0)

        mask[:, :, :, i] = mask_ #collect all masks to array
        i += 1

    i = 0
    for i in range(AUGMANTED_IMAGES_NUMBER):
        augmented_image, augmented_mask = seq(image=img, segmentation_maps=mask)`

**Comment by MikitaBelikau** [comment]
Alexander, it helped!I really appreciate it. Thank you very much. Regards,Mikita 14.07.2020, 00:16, "Alexander Jung" <notifications@github.com>: Hey, sorry for the late reply. I'm very busy currently with other things.Following your mail I assume that what you want to achieve is to augment exactly 1 image and N masks on that image. If all of these masks have the same height and width you can merge them to a single array of shape (1, H, W, N). Each channel (i.e. the fourth axis, N) would then contain one of these mask's content. The augmentation would happen according to seq(image=<image array>, segmentation_maps=<(1, H, W, N) array>). Make sure here that you use image=..., not imageS=... as you only have a single image.If your masks have different heights and widths it gets a little bit more complicated. Then you have to use something like the following:image = <image array>
masks_oi = [ia.SegmentationMasksOnImage(mask, shape=image.shape) for mask in masks]
seq_det = seq.to_deterministic()
image_aug = seq_det(image=image)
masks_aug = [seq_det(segmentation_masks=mask_oi).get_arr() for mask_oi in in masks_oi]Essentially you "freeze" the random number generator via to_deterministic() so that it auto-resets itself after each augmentation call. This way you can make multiple calls and get every time the same augmentations, just applied to different inputs. Make sure to call to_deterministic() once per batch, otherwise you would always get the same augmentations for every batch.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
