### ISSUE TITLE
Help: Can you review the filters learned by my algorithm?

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#7]
I know there has to be a limit to asking questions.
But I am working on a new feature learning methodology.

My algorithm has learned this following set of filters on MNIST. I was hoping you could give me a second opinion over how good these filters are.

[features_1.pdf](https://github.com/aleju/imgaug/files/655587/features_1.pdf)
[features_2.pdf](https://github.com/aleju/imgaug/files/655588/features_2.pdf)

Also, which ones of the two seem better?

**Comment by aleju** [comment]
Maybe the second one looks better. They seem pretty equal to me.
Best way to find out which one is better is to test them.

**Comment by SarthakYadav** [comment]
I just did. In order to evaluate solely these features, I added these weights as first layer weights, froze the layer and then added a softmax layer to the network.

The network with the second set of features gave about a 1% better accuracy.
