### ISSUE TITLE
ValueError: could not broadcast input array from shape (1024,768,3) into shape (768,1024,3)

### ISSUE THREAD

**Issue by sdikby** [aleju/imgaug#70]
I get this error when cropping an image
https://github.com/aleju/imgaug/blob/27785f4c8d8d4083349e980c75571e4e1c54ff98/imgaug/imgaug.py#L518

I think it should be `(height, width)` to match `result = np.zeros((nb_images, height, width, nb_channels), dtype=np.uint8)`

**Comment by aleju** [comment]
Can you post a stacktrace? According to all examples I can find `cv2.resize` uses (width, height) and not (height, width).

**Comment by sdikby** [comment]
Oops ! my mistake. As i don't want to use cv2 for my use-case i switched to PIl and scipy. It's a refactoring mistake from my part.
I will close this issue then
