### ISSUE TITLE
ValueError: Got dtype 'float64', which is a forbidden dtype

### ISSUE THREAD

**Issue by harbarex** [aleju/imgaug#703]
I am using np.ndarrays to train a model using augmented images, but I keep getting the following error:

`ValueError: Got dtype 'float64', which is a forbidden dtype (bool, uint16, uint32, uint64, uint128, uint256, int8, int16, int32, int64, int128, int256, float16, float32, float64, float96, float128, float256).
`
What is the correct dtype for the imgaug model?

**Comment by wjacobward** [comment]
I believe it should be uint8. You can scale your array to [0, 255], then change its type with .astype(np.uint8).

**Comment by harbarex** [comment]
> I believe it should be uint8. You can scale your array to [0, 255], then change its type with .astype(np.uint8).

Yes that works. Thanks!
