### ISSUE TITLE
how to know which augmenters are used?

### ISSUE THREAD

**Issue by TyrionChou** [aleju/imgaug#706]
hi~,
    i want to know when i use (Someof), how to know which augmenters are used?
    thank you very much!
    and i got a problem it seem like that
    error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\core\src\alloc.app:72:error(-4:Insufficient memory) Failed to allocate ***** bytes in function 'cv::OutofMemoryError'

**Comment by wjacobward** [comment]
Take a look at this post https://github.com/aleju/imgaug/issues/275#issuecomment-468907493; @aleju mentions a way to determine which augmenters are used in a SomeOf() block.

As for the OpenCV error, the obvious question is "are you doing something that might exceed your free memory"?

**Comment by TyrionChou** [comment]
> Take a look at this post [#275 (comment)](https://github.com/aleju/imgaug/issues/275#issuecomment-468907493); @aleju mentions a way to determine which augmenters are used in a SomeOf() block.
> 
> As for the OpenCV error, the obvious question is "are you doing something that might exceed your free memory"?

thank you very much
