### ISSUE TITLE
generate N augemented images from one image

### ISSUE THREAD

**Issue by sdikby** [aleju/imgaug#71]
Hi, is it possible to generate N augmented images from one image given as input. If not could you please put me on the write path on how to tweak `imgaug `to make it possible.
I am only using `Sequential()` as meta augmenter.

Thank you for your effort implementing this cool library.

**Comment by aleju** [comment]
Just throw the image N times into the augmenters, e.g. something like
```python
aug = Sequential(...)
N = 16
image = np.zeros((64, 64, 3), dtype=np.uint8)

# use any of the following three ways:
images_aug = aug.augment_images([image] * N) # list with N times the image
images_aug = aug.augment_images(np.tile(image[np.newaxis, ...], (N, 1, 1, 1))) # array with N times the image
images_aug = [aug.augment_image(image) for _ in range(N)] # N augmentation runs
```

**Comment by sdikby** [comment]
Thank you for the answer. Sorry i was not clear.
Let us assume i have three images. Im1, Im2 and Im3. From each image i want to generate three augmented images  Im11, Im12 , Im13, Im21, Im22 ,etc...

To achieve this process, ie. from Im`i` -> Im`ij`, where `i `=number of input images and `j`= number of augmented images, i define the following meta augmenter
```
seq = ipm.Sequential([
    # 1st set of augmenters
    ipm.Fliplr(),
    ipm.Flipud(),
    ipm.Crop((4, 7, 8, 5)),
    ipm.Affine(
        scale={"x": 1.2, "y": 0.8},
        translate_percent={"x": 0.2, "y": -0.2},
        rotate=90
    ),
    # 2st set of augmenters
    ipm.Sequential(
        ipm.Affine(
            rotate=-45
        )
    ),
    # 3rd set of augmenters
    ipm.Sequential(
        ipm.Affine(
            rotate=-45
        ),
        ipm.Flipud()
    )
])
```
Where then number of augmenters set in` ipm.Sequential(...)` matches our `j` and each set of augmenters generates one image.

I hope that this time i have succeeded to express my thoughts as clear as possible, or not?

**Comment by aleju** [comment]
That sounds like you have essentially three different augmentation pipelines? Then you should just define three Sequentials and apply each of them on their own -- no need to wrap them in one big Sequential.

You could also name the Sequentials (`Sequential(..., name="examplename")`) and then use three augmentation runs and each time use `hooks` to activate/deactive specific Sequentials. But that seems like a rather convoluted solution.

Btw, you are using static values for all augmenters. E.g. `Affine(rotate=-45)` rotates every image by -45 degrees. You probably want `Affine(rotate=(-45, 45))` (rotate by -45 to 45 degrees) and `Fliplr(0.5)` (flip 50% of all images, `Fliplr()` flips 0% by default).

**Comment by sdikby** [comment]
I have just implemented what you said. First i defined my pipelines, then i loaded my images and finally for each image i execute the defined pipelines. thanks!
