### ISSUE TITLE
image size changed

### ISSUE THREAD

**Issue by kli017** [aleju/imgaug#73]
Hello I am using imgaug do image augmentation on my image set and my code is like this
`for char in path:
    subdir = root+'/'+ data +'/'+char
    childpath = os.listdir(subdir)
    for child in childpath:
        subpath = data+'/' +char + '/'+child
        d = ' %s' %(i)
        t = subpath + d
        img_pil = Image.open(subpath)
        images = np.array(img_pil)
        seq = iaa.Sequential([iaa.GaussianBlur((0, 0.5)),
                              iaa.ContrastNormalization((0.75, 1.5)),
							  iaa.AverageBlur(k=(2, 7))
		])
		
        images_aug = seq.augment_images([images])[0]
        new_img = np.array(images_aug)
        scipy.misc.imsave(subpath +'au.jpg', new_img)
        print new_img.shape
`
my input image is 32by32by3 but the size of output image became 33by32by3??
anyone know what happened here?

**Comment by aleju** [comment]
Can you check whether your input images are really all 32x32x3 and maybe write a minimal working example? I tried the below (similar) code and didn't get any such problem:
```python
from __future__ import print_function
from imgaug import augmenters as iaa
import imgaug as ia

image = ia.quokka(size=(32, 32))

seq = iaa.Sequential([
    iaa.GaussianBlur((0, 0.5)),
    iaa.ContrastNormalization((0.75, 1.5)),
    iaa.AverageBlur(k=(2, 7))
])

for _ in xrange(100):
    image_aug = seq.augment_images([image])[0]
    print(image.shape, image_aug.shape, "changed" if image.shape != image_aug.shape else "OK")
```

Output:
```
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
(32, 32, 3) (32, 32, 3) OK
```

**Comment by kli017** [comment]
hello! thank you for reminding me to check out my images. Just found the reason is the image generate code has some problem so some images became (32,33,3). The augmentation part worked fine... sorry

**Comment by aleju** [comment]
If it is just a single image you can do something like
```python
image_aug = seq.augment_image(image)
scipy.misc.imsave("save/to/directory/image.jpg", image_aug)
```
or
```python
image_aug = seq.augment_images([image])[0]
scipy.misc.imsave("save/to/directory/image.jpg", image_aug)
```

If it is multiple images you can do something like
```python
images_aug = seq.augment_images(images)
for i, image_aug in enumerate(images_aug):
    scipy.misc.imsave("save/to/directory/%06d" % (i,), image_aug)
```

**Comment by kli017** [comment]
thank you so much, that helped a lot. I was wondering for the shear and rotate in Affine . Can I fill the background with 255(white pixel)? I read the Docs but cannot find the parameter about that in those function

**Comment by aleju** [comment]
That should work with `Affine(shear=..., rotate=..., mode="constant", cval=255)` . Fills all newly created pixels with RGB (255, 255, 255).

**Comment by iliya-hajjar** [comment]
I have the same problem but the shape of my images (1, 160, 160, 3) before and after augmentation is the same.However I can not save the images with "scipy.misc.imsave", getting the following error :
"ValueError: 'arr' does not have a suitable array shape for any mode."
And when I'm trying to use indexing like what you did  "seq.augment_images([image])[0]" the output is:
"assert images.ndim == 4"
Is there anyway to solve this problem ?

**Comment by aleju** [comment]
If your `image` variable already has shape `(1, 160, 160, 3)` instead of `(160, 160, 3)` you need to use `imsave()` with `image[0]` and can directly use `seq.augment_images(image)[0]` without the `[image]`.

**Comment by iliya-hajjar** [comment]
I've solved the problem by dropping the first dimension and changing the following lines:
images_aug = seq.augment_images([img])
imsave('aug-image.png', images_aug[0])
