### ISSUE TITLE
Confusing "percent" terminology

### ISSUE THREAD

**Issue by isarandi** [aleju/imgaug#74]
Some functions, like CoarseDropout and CoarseSalt etc. have a size_percent parameter, but they are actually interpreted as fractions, not percentages. A percentage would range from 0 to 100, but these values range from 0 to 1.

**Comment by aleju** [comment]
Using float values between `0.0` and `1.0` to represent percentages is pretty much standard afaik?
Or do you just mean that the values for Coarse* augmenters are basically inverted (small percentage = large areas & large percentages = small areas)?

**Comment by isarandi** [comment]
I think it's not standard. Usually "fraction" or "ratio" is used (in APIs as well) when it's a direct multiplier.
Of course it's unusual to have actual percentages (i.e. numbers that range from 1-100) in APIs (unless there's some restriction to integers), so I expected the parameters here to range from 0 to 1, but I still had to check the examples, because the naming looked unusual.
