### ISSUE TITLE
StochasticParameter should support __radd__, __rpow__ etc.

### ISSUE THREAD

**Issue by isarandi** [aleju/imgaug#76]
Currently only `__add__,` `__pow__` etc. are supported, which means expressions where the first operand is a number (such as `3/ia.Normal(0,1)`) don't work. This is especially a problem for expressions such as `2**ia.Uniform(-1,1)`. These can only be written as `ia.Deterministic(2)**ia.Uniform(-1,1)`, which is much less straightforward. This could be solved by implementing `__rpow__,` `__rdiv__` etc. on `StochasticParameter`.

Basically something like this could be added into StochasticParameter:

```
    @staticmethod
    def deterministic_if_single_number(x):
        if ia.is_single_number(x):
            return Deterministic(x)
        return x

    def __radd__(self, other):
        return self.deterministic_if_single_number(other) + self

    def __rsub__(self, other):
        return self.deterministic_if_single_number(other) - self

    def __rmul__(self, other):
        return self.deterministic_if_single_number(other) * self

    def __rpow__(self, other):
        return self.deterministic_if_single_number(other) ** self

    def __rdiv__(self, other):
        return self.deterministic_if_single_number(other) / self

    def __rtruediv__(self, other):
        return self.deterministic_if_single_number(other) / self
```

**Comment by aleju** [comment]
Thanks for pointing this out. This should now work with the latest version.
