### ISSUE TITLE
Keypoint transformation while doing fliplr

### ISSUE THREAD

**Issue by baheytharwat** [aleju/imgaug#769]
Thank you guys for the great work! your efforts are appreciated. 
I wanted to do some transformation on an image and transform a keypoint with the same transformation. so I used 
```
        seq = iaa.Sequential([
            iaa.Fliplr(0.5), # horizontal flips
            iaa.Affine(
                rotate=10,
                scale={"x": (0.8, 1.2), "y": (0.8, 1.2)},
            ) # rotate by exactly 10deg and scale to 50-70%, affects keypoints
        ])


          kps = KeypointsOnImage([
              Keypoint(x=center[0], y=center[1])
          ], shape=img.shape)
          
          img, kps = seq(image=img, keypoints=kps)
          center[0] = kps.keypoints[0].x
          center[1] = kps.keypoints[0].y
```
But I noticed that there are some problems with the `Fliplr`,  the x component is not transformed by the flipping. I expect the new x should be  img width - old x. I see the x doesn't change and the transformation(Rotation and scale) works fine without the flipping.

**Comment by Cospel** [comment]
Anyone solved this?

**Comment by jren03** [comment]
I've also observed something similar in `imgaug == 0.4.0`. Curious if there's been a solution to this?
