### ISSUE TITLE
Modes in Elastic Transform

### ISSUE THREAD

**Issue by kacper1095** [aleju/imgaug#93]
After in-depth analysis of results from Elastic Transform it would be great to add possibility to choose modes of interpolation in Elastic Transform augmenter. To me, 'wrap' mode gave the most desired results. It shouldn't be a big deal to add it:
- additional parameter in ElasticTransform: 'mode'
- assign to field: self.mode = mode
- in map_coordinates method: 
from:
```
remapped_flat = ndimage.interpolation.map_coordinates(image[..., c], (indices_x, indices_y), order=1)
```
to:
```
remapped_flat = ndimage.interpolation.map_coordinates(image[..., c], (indices_x, indices_y), mode=self.mode, order=1)
```

Thanks in advance!

**Comment by aleju** [comment]
Thanks for the suggestion. ElasticTransformation now supports `mode`, `order` and `cval`.
