### ISSUE TITLE
Great Augmentation library

### ISSUE THREAD

**Issue by akanimax** [aleju/imgaug#95]
I am not sure of the bugs that may be there, But till date, this is the best augmentation library I have encountered so far. The api is extremely readable and intuitive to understand.

It is ironic, that I am opening an issue to commend the job done.  :+1: 
Well, no option of comments on github. Please close this issue as soon as you read it. 

Cheers!
Akanimax

**Comment by aleju** [comment]
Thanks a lot! :blush:
Good to hear that the library helps somebody!
