### ISSUE TITLE
when i rotate a image by 30°，some of the content disappear...

### ISSUE THREAD

**Issue by xiaoxiongli** [aleju/imgaug#98]
when i rotate a image by 30°，some of the content disappear...
what i want is get a bigger image which contain all of the content in the original pictures.

Minimum Bounding Rectangle

Does this code support this feature?

**Comment by aleju** [comment]
No, that's not supported. There's currently a PR for scikit-image to add that functionality, but it is waiting for merge since several months now.

**Comment by xiaoxiongli** [comment]
@aleju  thank you all the same，happy Chinese new year！

**Comment by aleju** [comment]
Happy new year to you too!
I close this for now.
